### Controlling the Keyboard and Mouse with GUI Automation

Knowing various Python modules for editing spreadsheets, downloading files, and launching programs is useful, but sometimes there just aren’t any modules for the applications you need to work with. The ultimate tools for automating tasks on your computer are programs you write that directly control the keyboard and mouse. These programs can control other applications by sending them virtual keystrokes and mouse clicks, justpython3- as if you were sitting at your computer and interacting with the applications yourself. This technique is known as graphical user interface automation, or GUI automation for short. With GUI automation, your programs can do anything that a human user sitting at the computer can do, except spill coffee on the keyboard.

Think of GUI automation as programming a robotic arm. You can program the robotic arm to type at your keyboard and move your mouse for you. This technique is particularly useful for tasks that involve a lot of mindless clicking or filling out of forms.

The pyautogui module has functions for simulating mouse movements, button clicks, and scrolling the mouse wheel. This chapter covers only a subset of PyAutoGUI’s features; you can find the full documentation at http://pyautogui.readthedocs.org/.

### Installing the pyautogui Module

The pyautogui module can send virtual keypresses and mouse clicks to Windows, OS X, and Linux. Depending on which operating system you’re using, you may have to install some other modules (called dependencies) before you can install PyAutoGUI.

    On Windows, there are no other modules to install.

    On OS X, run sudo pip3 install pyobjc-framework-Quartz, sudo pip3 install pyobjc-core, and then sudo pip3 install pyobjc.

    On Linux, run sudo pip3 install python3-xlib, sudo apt-get install scrot, sudo apt-get install python3-tk, and sudo apt-get install python3-dev. (Scrot is a screenshot program that PyAutoGUI uses.)

After these dependencies are installed, run pip install pyautogui (or pip3 on OS X and Linux) to install PyAutoGUI.

Appendix A has complete information on installing third-party modules. To test whether PyAutoGUI has been installed correctly, run import pyautogui from the interactive shell and check for any error messages.

### Staying on Track

Before you jump in to a GUI automation, you should know how to escape problems that may arise. Python can move your mouse and type keystrokes at an incredible speed. In fact, it might be too fast for other programs to keep up with. Also, if something goes wrong but your program keeps moving the mouse around, it will be hard to tell what exactly the program is doing or how to recover from the problem. Like the enchanted brooms from Disney’s The Sorcerer’s Apprentice, which kept filling—and then overfilling—Mickey’s tub with water, your program could get out of control even though it’s following your instructions perfectly. Stopping the program can be difficult if the mouse is moving around on its own, preventing you from clicking the IDLE window to close it. Fortunately, there are several ways to prevent or recover from GUI automation problems.

### Shutting Down Everything by Logging Out

Perhaps the simplest way to stop an out-of-control GUI automation program is to log out, which will shut down all running programs. On Windows and Linux, the logout hotkey is CTRL-ALT-DEL. On OS X, it is -SHIFT-OPTION-Q. By logging out, you’ll lose any unsaved work, but at least you won’t have to wait for a full reboot of the computer.

### Pauses and Fail-Safes

You can tell your script to wait after every function call, giving you a short window to take control of the mouse and keyboard if something goes wrong. To do this, set the pyautogui.PAUSE variable to the number of seconds you want it to pause. For example, after setting pyautogui.PAUSE = 1.5, every PyAutoGUI function call will wait one and a half seconds after performing its action. Non-PyAutoGUI instructions will not have this pause.

PyAutoGUI also has a fail-safe feature. Moving the mouse cursor to the upper-left corner of the screen will cause PyAutoGUI to raise the pyautogui.FailSafeException exception. Your program can either handle this exception with try and except statements or let the exception crash your program. Either way, the fail-safe feature will stop the program if you quickly move the mouse as far up and left as you can. You can disable this feature by setting pyautogui.FAILSAFE = False.

In [2]:
import pyautogui as pag
pag.PAUSE = 1
pag.FAILSAFE = True

The mouse functions of PyAutoGUI use x- and y-coordinates. Figure 18-1 shows the coordinate system for the computer screen; it’s similar to the coordinate system used for images, discussed in Chapter 17. The origin, where x and y are both zero, is at the upper-left corner of the screen. The x-coordinates increase going to the right, and the y-coordinates increase going down. All coordinates are positive integers; there are no negative coordinates.

Your resolution is how many pixels wide and tall your screen is. If your screen’s resolution is set to 1920×1080, then the coordinate for the upper-left corner will be (0, 0), and the coordinate for the bottom-right corner will be (1919, 1079).

The pyautogui.size() function returns a two-integer tuple of the screen’s width and height in pixels. 

In [3]:
import pyautogui as pag
pag.size()

Size(width=3440, height=1440)

In [7]:
# Store the width and height variables
width, height = pag.size()

In [8]:
width

3440

In [9]:
height

1440

### Moving the Mouse

Now that you understand screen coordinates, let’s move the mouse. The pyautogui.moveTo() function will instantly move the mouse cursor to a specified position on the screen. Integer values for the x- and y-coordinates make up the function’s first and second arguments, respectively. An optional duration integer or float keyword argument specifies the number of seconds it should take to move the mouse to the destination. If you leave it out, the default is 0 for instantaneous movement. (All of the duration keyword arguments in PyAutoGUI functions are optional.) 

In [11]:
import pyautogui as pag

# Move the mouse cursor clockwise in a square pattern in four coordinates 5 times
for i in range(5):
    pag.moveTo(100, 100, duration = 0.25) # quarter of a second movement
    pag.moveTo(200, 100, duration = 0.25) # quarter of a second movement
    pag.moveTo(200, 200, duration = 0.25) # quarter of a second movement
    pag.moveTo(100, 200, duration = 0.25) # quarter of a second movement
    
exit()

The pyautogui.moveRel() function moves the mouse cursor relative to its current position. The following example moves the mouse in the same square pattern, except it begins the square from wherever the mouse happens to be on the screen when the code starts running

In [4]:
import pyautogui as pag

# Move mouse cursor relative to it's current position
for i in range(3):
    pag.moveRel(250, 0, duration = 0.1)
    pag.moveRel(0, 250, duration = 0.1)
    pag.moveRel(-250, 0, duration = 0.1)
    pag.moveRel(0, -250, duration = 0.1)

pyautogui.moveRel() also takes three arguments: how many pixels to move horizontally to the right, how many pixels to move vertically downward, and (optionally) how long it should take to complete the movement. A negative integer for the first or second argument will cause the mouse to move left or upward, respectively.

### Getting the Mouse Position

You can determine the mouse’s current position by calling the pyautogui.position() function, which will return a tuple of the mouse cursor’s x and y positions at the time of the function call.

In [5]:
import pyautogui as pag

pag.position()

Point(x=1514, y=1258)

In [9]:
type(pag.position())

pyautogui.Point

In [10]:
import pyautogui as pag

# Move mouse cursor relative to it's current position
for i in range(3):
    pag.moveRel(250, 0, duration = 0.1)
    print(str(pag.position()))
    pag.moveRel(0, 250, duration = 0.1)
    print(str(pag.position()))
    pag.moveRel(-250, 0, duration = 0.1)
    print(str(pag.position()))
    pag.moveRel(0, -250, duration = 0.1)
    print(str(pag.position()))

Point(x=1748, y=1081)
Point(x=1748, y=1331)
Point(x=1498, y=1331)
Point(x=1498, y=1081)
Point(x=1748, y=1081)
Point(x=1748, y=1331)
Point(x=1498, y=1331)
Point(x=1498, y=1081)
Point(x=1748, y=1081)
Point(x=1748, y=1331)
Point(x=1498, y=1331)
Point(x=1498, y=1081)


### Project: “Where Is the Mouse Right Now?”

Being able to determine the mouse position is an important part of setting up your GUI automation scripts. But it’s almost impossible to figure out the exact coordinates of a pixel just by looking at the screen. It would be handy to have a program that constantly displays the x- and y-coordinates of the mouse cursor as you move it around.

At a high level, here’s what your program should do:

    Display the current x- and y-coordinates of the mouse cursor.

    Update these coordinates as the mouse moves around the screen.

This means your code will need to do the following:

    Call the position() function to fetch the current coordinates.

    Erase the previously printed coordinates by printing \b backspace characters to the screen.

    Handle the KeyboardInterrupt exception so the user can press CTRL-C to quit.



### Step 1: Import the Module

In [11]:
import pyautogui as pag

### Step 2: Set Up the Quit Code and Infinite Loop
You can use an infinite while loop to constantly print the current mouse coordinates from mouse.position(). As for the code that quits the program, you’ll need to catch the KeyboardInterrupt exception, which is raised whenever the user presses CTRL-C. If you don’t handle this exception, it will display an ugly traceback and error message to the user

In [14]:
import pyautogui as pag

print('Press Ctrl-C to quit.')
try:
    while True:

except KeyboardInterrupt:
    print('\nDone.')


IndentationError: expected an indented block (<ipython-input-14-c1cef9b7c141>, line 7)

### Step 3: Get and Print the Mouse Coordinates

The code inside the while loop should get the current mouse coordinates, format them to look nice, and print them. Add the following code to the inside of the while loop

In [11]:
#! python3
# mouseNow.py - Displays the mouse cursor's current position.

import pyautogui
import time

print('Press Ctrl-C to quit.')
time_elapsed = 0
start_time = time.time()

try:
    while time_elapsed < 10:
        # Get and print the mouse coordinates.
        x, y = pyautogui.position()
        positionStr = 'X: ' + str(x).rjust(4) + ' Y: ' + str(y).rjust(4) # rjust() = padding
        print(positionStr, end='')
        # Always pass flush=True to print() calls that print \b backspace characters. 
        print('\b' * len(positionStr), end=' - ', flush=True)
        time_elapsed = time.time() - start_time
        time.sleep(1)
        print('%s seconds has passed...' % (round(time_elapsed,0)))

except KeyboardInterrupt:
    print('\nDone.')
    
print('Finished')


Press Ctrl-C to quit.
X: 1612 Y:  58 - 0.0 seconds has passed...
X: 1564 Y:  68 - 1.0 seconds has passed...
X: 1558 Y:  70 - 2.0 seconds has passed...
X: 1431 Y:  83 - 3.0 seconds has passed...
X: 1559 Y:  90 - 4.0 seconds has passed...
X: 1315 Y:  95 - 5.0 seconds has passed...
X: 1380 Y:  64 - 6.0 seconds has passed...
X: 1741 Y:  57 - 7.0 seconds has passed...
X: 1888 Y:  73 - 8.0 seconds has passed...
X: 1559 Y:  95 - 9.0 seconds has passed...
X: 1621 Y:  65 - 10.0 seconds has passed...
Finished


This actually prints positionStr to the screen. The end='' keyword argument to print() prevents the default newline character from being added to the end of the printed line. It’s possible to erase text you’ve already printed to the screen—but only for the most recent line of text. Once you print a newline character, you can’t erase anything printed before it.

To erase text, print the \b backspace escape character. This special character erases a character at the end of the current line on the screen. The line at ❶ uses string replication to produce a string with as many \b characters as the length of the string stored in positionStr, which has the effect of erasing the positionStr string that was last printed.

For a technical reason beyond the scope of this book, always pass flush=True to print() calls that print \b backspace characters. Otherwise, the screen might not update the text as desired.

Since the while loop repeats so quickly, the user won’t actually notice that you’re deleting and reprinting the whole number on the screen. For example, if the x-coordinate is 563 and the mouse moves one pixel to the right, it will look like only the 3 in 563 is changed to a 4.

### Controlling Mouse Interaction

Now that you know how to move the mouse and figure out where it is on the screen, you’re ready to start clicking, dragging, and scrolling.

### Clicking the Mouse

To send a virtual mouse click to your computer, call the pyautogui.click() method. By default, this click uses the left mouse button and takes place wherever the mouse cursor is currently located. You can pass x- and y-coordinates of the click as optional first and second arguments if you want it to take place somewhere other than the mouse’s current position.

If you want to specify which mouse button to use, include the button keyword argument, with a value of 'left', 'middle', or 'right'. For example, pyautogui.click(100, 150, button='left') will click the left mouse button at the coordinates (100, 150), while pyautogui.click(200, 250, button='right') will perform a right-click at (200, 250).

In [12]:
import pyautogui as pag

# Click check
pag.click(10, 5) # pyautogui.click(100, 150, button='left') for left mouse clicks

In [13]:
import pyautogui as pag

# Move 250 to the right and click
pag.moveRel(250, 0, duration = 0.1)
pag.click()

You should see the mouse pointer move to near the top-left corner of your screen and click once. A full “click” is defined as pushing a mouse button down and then releasing it back up without moving the cursor. You can also perform a click by calling pyautogui.mouseDown(), which only pushes the mouse button down, and pyautogui.mouseUp(), which only releases the button. These functions have the same arguments as click(), and in fact, the click() function is just a convenient wrapper around these two function calls.

As a further convenience, the pyautogui.doubleClick() function will perform two clicks with the left mouse button, while the pyautogui.rightClick() and pyautogui.middleClick() functions will perform a click with the right and middle mouse buttons, respectively.

### Dragging the Mouse

Dragging means moving the mouse while holding down one of the mouse buttons. For example, you can move files between folders by dragging the folder icons, or you can move appointments around in a calendar app.

PyAutoGUI provides the pyautogui.dragTo() and pyautogui.dragRel() functions to drag the mouse cursor to a new location or a location relative to its current one. The arguments for dragTo() and dragRel() are the same as moveTo() and moveRel(): the x-coordinate/horizontal movement, the y-coordinate/vertical movement, and an optional duration of time. (OS X does not drag correctly when the mouse moves too quickly, so passing a duration keyword argument is recommended.)

To try these functions, open a graphics-drawing application such as Paint on Windows, Paintbrush on OS X, or GNU Paint on Linux. (If you don’t have a drawing application, you can use the online one at http://sumopaint.com/.) I will use PyAutoGUI to draw in these applications.

With the mouse cursor over the drawing application’s canvas and the Pencil or Brush tool selected

In [14]:
#! python 3
# spiralDraw.py

import pyautogui as pag
import time

pag.click()
distance = 20
while distance > 0:
    pag.dragRel(distance, 0, duration = 0.2) # move right
    distance = distance - 5
    pag.dragRel(-distance, 0, duration = 0.2) # move left
    distance = distance - 5
    pag.dragRel(0, -distance, duration = 0.2) # move up

When you run this program, there will be a five-second delay ❶ for you to move the mouse cursor over the drawing program’s window with the Pencil or Brush tool selected. Then spiralDraw.py will take control of the mouse and click to put the drawing program in focus ❷. A window is in focus when it has an active blinking cursor, and the actions you take—like typing or, in this case, dragging the mouse—will affect that window. Once the drawing program is in focus, spiralDraw.py draws a square spiral pattern 

The distance variable starts at 200, so on the first iteration of the while loop, the first dragRel() call drags the cursor 200 pixels to the right, taking 0.2 seconds ❸. distance is then decreased to 195 ❹, and the second dragRel() call drags the cursor 195 pixels down ❺. The third dragRel() call drags the cursor –195 horizontally (195 to the left) ❻, distance is decreased to 190, and the last dragRel() call drags the cursor 190 pixels up. On each iteration, the mouse is dragged right, down, left, and up, and distance is slightly smaller than it was in the previous iteration. By looping over this code, you can move the mouse cursor to draw a square spiral.

You could draw this spiral by hand (or rather, by mouse), but you’d have to work slowly to be so precise. PyAutoGUI can do it in a few seconds!

### Scrolling the Mouse

The final PyAutoGUI mouse function is scroll(), which you pass an integer argument for how many units you want to scroll the mouse up or down. The size of a unit varies for each operating system and application, so you’ll have to experiment to see exactly how far it scrolls in your particular situation. The scrolling takes place at the mouse cursor’s current position. Passing a positive integer scrolls up, and passing a negative integer scrolls down.

In [17]:
pyautogui.scroll(200)

In [21]:
import pyperclip

numbers = ''
for i in range(200):
    numbers = numbers + str(i) + '\n'

In [22]:
pyperclip.paste()

'pyperclip'

In [23]:
pyperclip.copy(numbers) # Copies numbers 0 - 199 to clipboard

This imports pyperclip and sets up an empty string, numbers. The code then loops through 200 numbers and adds each number to numbers, along with a newline. After pyperclip.copy(numbers), the clipboard will be loaded with 200 lines of numbers. Open a new file editor window and paste the text into it. This will give you a large text window to try scrolling in.

In [24]:
import time
import pyautogui as pag

time.sleep(1)
pag.scroll(100)

On the second line, you enter two commands separated by a semicolon, which tells Python to run the commands as if they were on separate lines. The only difference is that the interactive shell won’t prompt you for input between the two instructions. This is important for this example because we want to the call to pyautogui.scroll() to happen automatically after the wait. (Note that while putting two commands on one line can be useful in the interactive shell, you should still have each instruction on a separate line in your programs.)

After pressing ENTER to run the code, you will have five seconds to click the file editor window to put it in focus. Once the pause is over, the pyautogui.scroll() call will cause the file editor window to scroll up after the five-second delay.

### Working with the Screen

Your GUI automation programs don’t have to click and type blindly. PyAutoGUI has screenshot features that can create an image file based on the current contents of the screen. These functions can also return a Pillow Image object of the current screen’s appearance. If you’ve been skipping around in this book, you’ll want to read Chapter 17 and install the pillow module before continuing with this section.

On Linux computers, the scrot program needs to be installed to use the screenshot functions in PyAutoGUI. In a Terminal window, run sudo apt-get install scrot to install this program. If you’re on Windows or OS X, skip this step and continue with the section.

### Getting a Screenshot

To take screenshots in Python, call the pyautogui.screenshot() function. 

In [26]:
import pyautogui as pag

# Take a screenshot()
img = pyautogui.screenshot()

# Get pixels (tuple of coordinates) of the image object
print(img.getpixel((0, 0)))
print(img.getpixel((50, 200)))

(43, 43, 43)
(255, 254, 238)


Pass getpixel() a tuple of coordinates, like (0, 0) or (50, 200), and it’ll tell you the color of the pixel at those coordinates in your image. The return value from getpixel() is an RGB tuple of three integers for the amount of red, green, and blue in the pixel. (There is no fourth value for alpha, because screenshot images are fully opaque.) 

This is how your programs can “see” what is currently on the screen.

### Analyzing the Screenshot

Say that one of the steps in your GUI automation program is to click a gray button. Before calling the click() method, you could take a screenshot and look at the pixel where the script is about to click. If it’s not the same gray as the gray button, then your program knows something is wrong. Maybe the window moved unexpectedly, or maybe a pop-up dialog has blocked the button. At this point, instead of continuing—and possibly wreaking havoc by clicking the wrong thing—your program can “see” that it isn’t clicking on the right thing and stop itself.

PyAutoGUI’s pixelMatchesColor() function will return True if the pixel at the given x- and y-coordinates on the screen matches the given color. The first and second arguments are integers for the x- and y-coordinates, and the third argument is a tuple of three integers for the RGB color the screen pixel must match.

In [27]:
import pyautogui as pag

img.getpixel((50, 200))

(255, 254, 238)

In [28]:
pag.pixelMatchesColor(50, 200, (130, 135, 144))

False

In [29]:
pag.pixelMatchesColor(50, 200, (255, 135, 144))

False

In [30]:
import pyautogui as pag

img.getpixel((50, 200))

# Check
pag.pixelMatchesColor(50, 200, (130, 135, 144))
pag.pixelMatchesColor(50, 200, (255, 135, 144))

False

After taking a screenshot and using getpixel() to get an RGB tuple for the color of a pixel at specific coordinates ❶, pass the same coordinates and RGB tuple to pixelMatchesColor() ❷, which should return True. Then change a value in the RGB tuple and call pixelMatchesColor() again for the same coordinates ❸. This should return false. This method can be useful to call whenever your GUI automation programs are about to call click(). Note that the color at the given coordinates must exactly match. If it is even slightly different—for example, (255, 255, 254) instead of (255, 255, 255)—then pixelMatchesColor() will return False.

### Project: Extending the mouseNow Program

You could extend the mouseNow.py project from earlier in this chapter so that it not only gives the x- and y-coordinates of the mouse cursor’s current position but also gives the RGB color of the pixel under the cursor. 