allData = {'AK': {},
 'AL': {},
 'AR': {},
 'AZ': {},
 'Abbeville': {'pop': 0, 'tracts': 0},
 'Acadia': {'pop': 0, 'tracts': 0},
 'Accomack': {'pop': 0, 'tracts': 0},
 'Ada': {'pop': 0, 'tracts': 0},
 'Adair': {'pop': 0, 'tracts': 0},
 'Adams': {'pop': 0, 'tracts': 0},
 'Addison': {'pop': 0, 'tracts': 0},
 'Aiken': {'pop': 0, 'tracts': 0},
 'Aitkin': {'pop': 0, 'tracts': 0},
 'Alachua': {'pop': 0, 'tracts': 0},
 'Alamance': {'pop': 0, 'tracts': 0},
 'Alameda': {'pop': 0, 'tracts': 0},
 'Alamosa': {'pop': 0, 'tracts': 0},
 'Albany': {'pop': 0, 'tracts': 0},
 'Albemarle': {'pop': 0, 'tracts': 0},
 'Alcona': {'pop': 0, 'tracts': 0},
 'Alcorn': {'pop': 0, 'tracts': 0},
 'Aleutians East': {'pop': 0, 'tracts': 0},
 'Aleutians West': {'pop': 0, 'tracts': 0},
 'Alexander': {'pop': 0, 'tracts': 0},
 'Alexandria': {'pop': 0, 'tracts': 0},
 'Alfalfa': {'pop': 0, 'tracts': 0},
 'Alger': {'pop': 0, 'tracts': 0},
 'Allamakee': {'pop': 0, 'tracts': 0},
 'Allegan': {'pop': 0, 'tracts': 0},
 'Allegany': {'pop': 0, 'tracts': 0},
 'Alleghany': {'pop': 0, 'tracts': 0},
 'Allegheny': {'pop': 0, 'tracts': 0},
 'Allen': {'pop': 0, 'tracts': 0},
 'Allendale': {'pop': 0, 'tracts': 0},
 'Alpena': {'pop': 0, 'tracts': 0},
 'Alpine': {'pop': 0, 'tracts': 0},
 'Amador': {'pop': 0, 'tracts': 0},
 'Amelia': {'pop': 0, 'tracts': 0},
 'Amherst': {'pop': 0, 'tracts': 0},
 'Amite': {'pop': 0, 'tracts': 0},
 'Anchorage': {'pop': 0, 'tracts': 0},
 'Anderson': {'pop': 0, 'tracts': 0},
 'Andrew': {'pop': 0, 'tracts': 0},
 'Andrews': {'pop': 0, 'tracts': 0},
 'Androscoggin': {'pop': 0, 'tracts': 0},
 'Angelina': {'pop': 0, 'tracts': 0},
 'Anne Arundel': {'pop': 0, 'tracts': 0},
 'Anoka': {'pop': 0, 'tracts': 0},
 'Anson': {'pop': 0, 'tracts': 0},
 'Antelope': {'pop': 0, 'tracts': 0},
 'Antrim': {'pop': 0, 'tracts': 0},
 'Apache': {'pop': 0, 'tracts': 0},
 'Appanoose': {'pop': 0, 'tracts': 0},
 'Appling': {'pop': 0, 'tracts': 0},
 'Appomattox': {'pop': 0, 'tracts': 0},
 'Aransas': {'pop': 0, 'tracts': 0},
 'Arapahoe': {'pop': 0, 'tracts': 0},
 'Archer': {'pop': 0, 'tracts': 0},
 'Archuleta': {'pop': 0, 'tracts': 0},
 'Arenac': {'pop': 0, 'tracts': 0},
 'Arkansas': {'pop': 0, 'tracts': 0},
 'Arlington': {'pop': 0, 'tracts': 0},
 'Armstrong': {'pop': 0, 'tracts': 0},
 'Aroostook': {'pop': 0, 'tracts': 0},
 'Arthur': {'pop': 0, 'tracts': 0},
 'Ascension': {'pop': 0, 'tracts': 0},
 'Ashe': {'pop': 0, 'tracts': 0},
 'Ashland': {'pop': 0, 'tracts': 0},
 'Ashley': {'pop': 0, 'tracts': 0},
 'Ashtabula': {'pop': 0, 'tracts': 0},
 'Asotin': {'pop': 0, 'tracts': 0},
 'Assumption': {'pop': 0, 'tracts': 0},
 'Atascosa': {'pop': 0, 'tracts': 0},
 'Atchison': {'pop': 0, 'tracts': 0},
 'Athens': {'pop': 0, 'tracts': 0},
 'Atkinson': {'pop': 0, 'tracts': 0},
 'Atlantic': {'pop': 0, 'tracts': 0},
 'Atoka': {'pop': 0, 'tracts': 0},
 'Attala': {'pop': 0, 'tracts': 0},
 'Audrain': {'pop': 0, 'tracts': 0},
 'Audubon': {'pop': 0, 'tracts': 0},
 'Auglaize': {'pop': 0, 'tracts': 0},
 'Augusta': {'pop': 0, 'tracts': 0},
 'Aurora': {'pop': 0, 'tracts': 0},
 'Austin': {'pop': 0, 'tracts': 0},
 'Autauga': {'pop': 0, 'tracts': 0},
 'Avery': {'pop': 0, 'tracts': 0},
 'Avoyelles': {'pop': 0, 'tracts': 0},
 'Baca': {'pop': 0, 'tracts': 0},
 'Bacon': {'pop': 0, 'tracts': 0},
 'Bailey': {'pop': 0, 'tracts': 0},
 'Baker': {'pop': 0, 'tracts': 0},
 'Baldwin': {'pop': 0, 'tracts': 0},
 'Ballard': {'pop': 0, 'tracts': 0},
 'Baltimore': {'pop': 0, 'tracts': 0},
 'Baltimore City': {'pop': 0, 'tracts': 0},
 'Bamberg': {'pop': 0, 'tracts': 0},
 'Bandera': {'pop': 0, 'tracts': 0},
 'Banks': {'pop': 0, 'tracts': 0},
 'Banner': {'pop': 0, 'tracts': 0},
 'Bannock': {'pop': 0, 'tracts': 0},
 'Baraga': {'pop': 0, 'tracts': 0},
 'Barber': {'pop': 0, 'tracts': 0},
 'Barbour': {'pop': 0, 'tracts': 0},
 'Barnes': {'pop': 0, 'tracts': 0},
 'Barnstable': {'pop': 0, 'tracts': 0},
 'Barnwell': {'pop': 0, 'tracts': 0},
 'Barren': {'pop': 0, 'tracts': 0},
 'Barron': {'pop': 0, 'tracts': 0},
 'Barrow': {'pop': 0, 'tracts': 0},
 'Barry': {'pop': 0, 'tracts': 0},
 'Bartholomew': {'pop': 0, 'tracts': 0},
 'Barton': {'pop': 0, 'tracts': 0},
 'Bartow': {'pop': 0, 'tracts': 0},
 'Bastrop': {'pop': 0, 'tracts': 0},
 'Bates': {'pop': 0, 'tracts': 0},
 'Bath': {'pop': 0, 'tracts': 0},
 'Baxter': {'pop': 0, 'tracts': 0},
 'Bay': {'pop': 0, 'tracts': 0},
 'Bayfield': {'pop': 0, 'tracts': 0},
 'Baylor': {'pop': 0, 'tracts': 0},
 'Beadle': {'pop': 0, 'tracts': 0},
 'Bear Lake': {'pop': 0, 'tracts': 0},
 'Beaufort': {'pop': 0, 'tracts': 0},
 'Beauregard': {'pop': 0, 'tracts': 0},
 'Beaver': {'pop': 0, 'tracts': 0},
 'Beaverhead': {'pop': 0, 'tracts': 0},
 'Becker': {'pop': 0, 'tracts': 0},
 'Beckham': {'pop': 0, 'tracts': 0},
 'Bedford': {'pop': 0, 'tracts': 0},
 'Bedford City': {'pop': 0, 'tracts': 0},
 'Bee': {'pop': 0, 'tracts': 0},
 'Belknap': {'pop': 0, 'tracts': 0},
 'Bell': {'pop': 0, 'tracts': 0},
 'Belmont': {'pop': 0, 'tracts': 0},
 'Beltrami': {'pop': 0, 'tracts': 0},
 'Ben Hill': {'pop': 0, 'tracts': 0},
 'Benewah': {'pop': 0, 'tracts': 0},
 'Bennett': {'pop': 0, 'tracts': 0},
 'Bennington': {'pop': 0, 'tracts': 0},
 'Benson': {'pop': 0, 'tracts': 0},
 'Bent': {'pop': 0, 'tracts': 0},
 'Benton': {'pop': 0, 'tracts': 0},
 'Benzie': {'pop': 0, 'tracts': 0},
 'Bergen': {'pop': 0, 'tracts': 0},
 'Berkeley': {'pop': 0, 'tracts': 0},
 'Berks': {'pop': 0, 'tracts': 0},
 'Berkshire': {'pop': 0, 'tracts': 0},
 'Bernalillo': {'pop': 0, 'tracts': 0},
 'Berrien': {'pop': 0, 'tracts': 0},
 'Bertie': {'pop': 0, 'tracts': 0},
 'Bethel': {'pop': 0, 'tracts': 0},
 'Bexar': {'pop': 0, 'tracts': 0},
 'Bibb': {'pop': 0, 'tracts': 0},
 'Bienville': {'pop': 0, 'tracts': 0},
 'Big Horn': {'pop': 0, 'tracts': 0},
 'Big Stone': {'pop': 0, 'tracts': 0},
 'Billings': {'pop': 0, 'tracts': 0},
 'Bingham': {'pop': 0, 'tracts': 0},
 'Black Hawk': {'pop': 0, 'tracts': 0},
 'Blackford': {'pop': 0, 'tracts': 0},
 'Bladen': {'pop': 0, 'tracts': 0},
 'Blaine': {'pop': 0, 'tracts': 0},
 'Blair': {'pop': 0, 'tracts': 0},
 'Blanco': {'pop': 0, 'tracts': 0},
 'Bland': {'pop': 0, 'tracts': 0},
 'Bleckley': {'pop': 0, 'tracts': 0},
 'Bledsoe': {'pop': 0, 'tracts': 0},
 'Blount': {'pop': 0, 'tracts': 0},
 'Blue Earth': {'pop': 0, 'tracts': 0},
 'Boise': {'pop': 0, 'tracts': 0},
 'Bolivar': {'pop': 0, 'tracts': 0},
 'Bollinger': {'pop': 0, 'tracts': 0},
 'Bon Homme': {'pop': 0, 'tracts': 0},
 'Bond': {'pop': 0, 'tracts': 0},
 'Bonner': {'pop': 0, 'tracts': 0},
 'Bonneville': {'pop': 0, 'tracts': 0},
 'Boone': {'pop': 0, 'tracts': 0},
 'Borden': {'pop': 0, 'tracts': 0},
 'Bosque': {'pop': 0, 'tracts': 0},
 'Bossier': {'pop': 0, 'tracts': 0},
 'Botetourt': {'pop': 0, 'tracts': 0},
 'Bottineau': {'pop': 0, 'tracts': 0},
 'Boulder': {'pop': 0, 'tracts': 0},
 'Boundary': {'pop': 0, 'tracts': 0},
 'Bourbon': {'pop': 0, 'tracts': 0},
 'Bowie': {'pop': 0, 'tracts': 0},
 'Bowman': {'pop': 0, 'tracts': 0},
 'Box Butte': {'pop': 0, 'tracts': 0},
 'Box Elder': {'pop': 0, 'tracts': 0},
 'Boyd': {'pop': 0, 'tracts': 0},
 'Boyle': {'pop': 0, 'tracts': 0},
 'Bracken': {'pop': 0, 'tracts': 0},
 'Bradford': {'pop': 0, 'tracts': 0},
 'Bradley': {'pop': 0, 'tracts': 0},
 'Branch': {'pop': 0, 'tracts': 0},
 'Brantley': {'pop': 0, 'tracts': 0},
 'Braxton': {'pop': 0, 'tracts': 0},
 'Brazoria': {'pop': 0, 'tracts': 0},
 'Brazos': {'pop': 0, 'tracts': 0},
 'Breathitt': {'pop': 0, 'tracts': 0},
 'Breckinridge': {'pop': 0, 'tracts': 0},
 'Bremer': {'pop': 0, 'tracts': 0},
 'Brevard': {'pop': 0, 'tracts': 0},
 'Brewster': {'pop': 0, 'tracts': 0},
 'Briscoe': {'pop': 0, 'tracts': 0},
 'Bristol': {'pop': 0, 'tracts': 0},
 'Bristol Bay': {'pop': 0, 'tracts': 0},
 'Broadwater': {'pop': 0, 'tracts': 0},
 'Bronx': {'pop': 0, 'tracts': 0},
 'Brooke': {'pop': 0, 'tracts': 0},
 'Brookings': {'pop': 0, 'tracts': 0},
 'Brooks': {'pop': 0, 'tracts': 0},
 'Broome': {'pop': 0, 'tracts': 0},
 'Broomfield': {'pop': 0, 'tracts': 0},
 'Broward': {'pop': 0, 'tracts': 0},
 'Brown': {'pop': 0, 'tracts': 0},
 'Brule': {'pop': 0, 'tracts': 0},
 'Brunswick': {'pop': 0, 'tracts': 0},
 'Bryan': {'pop': 0, 'tracts': 0},
 'Buchanan': {'pop': 0, 'tracts': 0},
 'Buckingham': {'pop': 0, 'tracts': 0},
 'Bucks': {'pop': 0, 'tracts': 0},
 'Buena Vista': {'pop': 0, 'tracts': 0},
 'Buffalo': {'pop': 0, 'tracts': 0},
 'Bullitt': {'pop': 0, 'tracts': 0},
 'Bulloch': {'pop': 0, 'tracts': 0},
 'Bullock': {'pop': 0, 'tracts': 0},
 'Buncombe': {'pop': 0, 'tracts': 0},
 'Bureau': {'pop': 0, 'tracts': 0},
 'Burke': {'pop': 0, 'tracts': 0},
 'Burleigh': {'pop': 0, 'tracts': 0},
 'Burleson': {'pop': 0, 'tracts': 0},
 'Burlington': {'pop': 0, 'tracts': 0},
 'Burnet': {'pop': 0, 'tracts': 0},
 'Burnett': {'pop': 0, 'tracts': 0},
 'Burt': {'pop': 0, 'tracts': 0},
 'Butler': {'pop': 0, 'tracts': 0},
 'Butte': {'pop': 0, 'tracts': 0},
 'Butts': {'pop': 0, 'tracts': 0},
 'CA': {},
 'CO': {},
 'CT': {},
 'Cabarrus': {'pop': 0, 'tracts': 0},
 'Cabell': {'pop': 0, 'tracts': 0},
 'Cache': {'pop': 0, 'tracts': 0},
 'Caddo': {'pop': 0, 'tracts': 0},
 'Calaveras': {'pop': 0, 'tracts': 0},
 'Calcasieu': {'pop': 0, 'tracts': 0},
 'Caldwell': {'pop': 0, 'tracts': 0},
 'Caledonia': {'pop': 0, 'tracts': 0},
 'Calhoun': {'pop': 0, 'tracts': 0},
 'Callahan': {'pop': 0, 'tracts': 0},
 'Callaway': {'pop': 0, 'tracts': 0},
 'Calloway': {'pop': 0, 'tracts': 0},
 'Calumet': {'pop': 0, 'tracts': 0},
 'Calvert': {'pop': 0, 'tracts': 0},
 'Camas': {'pop': 0, 'tracts': 0},
 'Cambria': {'pop': 0, 'tracts': 0},
 'Camden': {'pop': 0, 'tracts': 0},
 'Cameron': {'pop': 0, 'tracts': 0},
 'Camp': {'pop': 0, 'tracts': 0},
 'Campbell': {'pop': 0, 'tracts': 0},
 'Canadian': {'pop': 0, 'tracts': 0},
 'Candler': {'pop': 0, 'tracts': 0},
 'Cannon': {'pop': 0, 'tracts': 0},
 'Canyon': {'pop': 0, 'tracts': 0},
 'Cape Girardeau': {'pop': 0, 'tracts': 0},
 'Cape May': {'pop': 0, 'tracts': 0},
 'Carbon': {'pop': 0, 'tracts': 0},
 'Caribou': {'pop': 0, 'tracts': 0},
 'Carlisle': {'pop': 0, 'tracts': 0},
 'Carlton': {'pop': 0, 'tracts': 0},
 'Caroline': {'pop': 0, 'tracts': 0},
 'Carroll': {'pop': 0, 'tracts': 0},
 'Carson': {'pop': 0, 'tracts': 0},
 'Carson City': {'pop': 0, 'tracts': 0},
 'Carter': {'pop': 0, 'tracts': 0},
 'Carteret': {'pop': 0, 'tracts': 0},
 'Carver': {'pop': 0, 'tracts': 0},
 'Cascade': {'pop': 0, 'tracts': 0},
 'Casey': {'pop': 0, 'tracts': 0},
 'Cass': {'pop': 0, 'tracts': 0},
 'Cassia': {'pop': 0, 'tracts': 0},
 'Castro': {'pop': 0, 'tracts': 0},
 'Caswell': {'pop': 0, 'tracts': 0},
 'Catahoula': {'pop': 0, 'tracts': 0},
 'Catawba': {'pop': 0, 'tracts': 0},
 'Catoosa': {'pop': 0, 'tracts': 0},
 'Catron': {'pop': 0, 'tracts': 0},
 'Cattaraugus': {'pop': 0, 'tracts': 0},
 'Cavalier': {'pop': 0, 'tracts': 0},
 'Cayuga': {'pop': 0, 'tracts': 0},
 'Cecil': {'pop': 0, 'tracts': 0},
 'Cedar': {'pop': 0, 'tracts': 0},
 'Centre': {'pop': 0, 'tracts': 0},
 'Cerro Gordo': {'pop': 0, 'tracts': 0},
 'Chaffee': {'pop': 0, 'tracts': 0},
 'Chambers': {'pop': 0, 'tracts': 0},
 'Champaign': {'pop': 0, 'tracts': 0},
 'Chariton': {'pop': 0, 'tracts': 0},
 'Charles': {'pop': 0, 'tracts': 0},
 'Charles City': {'pop': 0, 'tracts': 0},
 'Charles Mix': {'pop': 0, 'tracts': 0},
 'Charleston': {'pop': 0, 'tracts': 0},
 'Charlevoix': {'pop': 0, 'tracts': 0},
 'Charlotte': {'pop': 0, 'tracts': 0},
 'Charlottesville': {'pop': 0, 'tracts': 0},
 'Charlton': {'pop': 0, 'tracts': 0},
 'Chase': {'pop': 0, 'tracts': 0},
 'Chatham': {'pop': 0, 'tracts': 0},
 'Chattahoochee': {'pop': 0, 'tracts': 0},
 'Chattooga': {'pop': 0, 'tracts': 0},
 'Chautauqua': {'pop': 0, 'tracts': 0},
 'Chaves': {'pop': 0, 'tracts': 0},
 'Cheatham': {'pop': 0, 'tracts': 0},
 'Cheboygan': {'pop': 0, 'tracts': 0},
 'Chelan': {'pop': 0, 'tracts': 0},
 'Chemung': {'pop': 0, 'tracts': 0},
 'Chenango': {'pop': 0, 'tracts': 0},
 'Cherokee': {'pop': 0, 'tracts': 0},
 'Cherry': {'pop': 0, 'tracts': 0},
 'Chesapeake': {'pop': 0, 'tracts': 0},
 'Cheshire': {'pop': 0, 'tracts': 0},
 'Chester': {'pop': 0, 'tracts': 0},
 'Chesterfield': {'pop': 0, 'tracts': 0},
 'Cheyenne': {'pop': 0, 'tracts': 0},
 'Chickasaw': {'pop': 0, 'tracts': 0},
 'Chicot': {'pop': 0, 'tracts': 0},
 'Childress': {'pop': 0, 'tracts': 0},
 'Chilton': {'pop': 0, 'tracts': 0},
 'Chippewa': {'pop': 0, 'tracts': 0},
 'Chisago': {'pop': 0, 'tracts': 0},
 'Chittenden': {'pop': 0, 'tracts': 0},
 'Choctaw': {'pop': 0, 'tracts': 0},
 'Chouteau': {'pop': 0, 'tracts': 0},
 'Chowan': {'pop': 0, 'tracts': 0},
 'Christian': {'pop': 0, 'tracts': 0},
 'Churchill': {'pop': 0, 'tracts': 0},
 'Cibola': {'pop': 0, 'tracts': 0},
 'Cimarron': {'pop': 0, 'tracts': 0},
 'Citrus': {'pop': 0, 'tracts': 0},
 'Clackamas': {'pop': 0, 'tracts': 0},
 'Claiborne': {'pop': 0, 'tracts': 0},
 'Clallam': {'pop': 0, 'tracts': 0},
 'Clare': {'pop': 0, 'tracts': 0},
 'Clarendon': {'pop': 0, 'tracts': 0},
 'Clarion': {'pop': 0, 'tracts': 0},
 'Clark': {'pop': 0, 'tracts': 0},
 'Clarke': {'pop': 0, 'tracts': 0},
 'Clatsop': {'pop': 0, 'tracts': 0},
 'Clay': {'pop': 0, 'tracts': 0},
 'Clayton': {'pop': 0, 'tracts': 0},
 'Clear Creek': {'pop': 0, 'tracts': 0},
 'Clearfield': {'pop': 0, 'tracts': 0},
 'Clearwater': {'pop': 0, 'tracts': 0},
 'Cleburne': {'pop': 0, 'tracts': 0},
 'Clermont': {'pop': 0, 'tracts': 0},
 'Cleveland': {'pop': 0, 'tracts': 0},
 'Clinch': {'pop': 0, 'tracts': 0},
 'Clinton': {'pop': 0, 'tracts': 0},
 'Cloud': {'pop': 0, 'tracts': 0},
 'Coahoma': {'pop': 0, 'tracts': 0},
 'Coal': {'pop': 0, 'tracts': 0},
 'Cobb': {'pop': 0, 'tracts': 0},
 'Cochise': {'pop': 0, 'tracts': 0},
 'Cochran': {'pop': 0, 'tracts': 0},
 'Cocke': {'pop': 0, 'tracts': 0},
 'Coconino': {'pop': 0, 'tracts': 0},
 'Codington': {'pop': 0, 'tracts': 0},
 'Coffee': {'pop': 0, 'tracts': 0},
 'Coffey': {'pop': 0, 'tracts': 0},
 'Coke': {'pop': 0, 'tracts': 0},
 'Colbert': {'pop': 0, 'tracts': 0},
 'Cole': {'pop': 0, 'tracts': 0},
 'Coleman': {'pop': 0, 'tracts': 0},
 'Coles': {'pop': 0, 'tracts': 0},
 'Colfax': {'pop': 0, 'tracts': 0},
 'Colleton': {'pop': 0, 'tracts': 0},
 'Collier': {'pop': 0, 'tracts': 0},
 'Collin': {'pop': 0, 'tracts': 0},
 'Collingsworth': {'pop': 0, 'tracts': 0},
 'Colonial Heights': {'pop': 0, 'tracts': 0},
 'Colorado': {'pop': 0, 'tracts': 0},
 'Colquitt': {'pop': 0, 'tracts': 0},
 'Columbia': {'pop': 0, 'tracts': 0},
 'Columbiana': {'pop': 0, 'tracts': 0},
 'Columbus': {'pop': 0, 'tracts': 0},
 'Colusa': {'pop': 0, 'tracts': 0},
 'Comal': {'pop': 0, 'tracts': 0},
 'Comanche': {'pop': 0, 'tracts': 0},
 'Concho': {'pop': 0, 'tracts': 0},
 'Concordia': {'pop': 0, 'tracts': 0},
 'Conecuh': {'pop': 0, 'tracts': 0},
 'Conejos': {'pop': 0, 'tracts': 0},
 'Contra Costa': {'pop': 0, 'tracts': 0},
 'Converse': {'pop': 0, 'tracts': 0},
 'Conway': {'pop': 0, 'tracts': 0},
 'Cook': {'pop': 0, 'tracts': 0},
 'Cooke': {'pop': 0, 'tracts': 0},
 'Cooper': {'pop': 0, 'tracts': 0},
 'Coos': {'pop': 0, 'tracts': 0},
 'Coosa': {'pop': 0, 'tracts': 0},
 'Copiah': {'pop': 0, 'tracts': 0},
 'Corson': {'pop': 0, 'tracts': 0},
 'Cortland': {'pop': 0, 'tracts': 0},
 'Coryell': {'pop': 0, 'tracts': 0},
 'Coshocton': {'pop': 0, 'tracts': 0},
 'Costilla': {'pop': 0, 'tracts': 0},
 'Cottle': {'pop': 0, 'tracts': 0},
 'Cotton': {'pop': 0, 'tracts': 0},
 'Cottonwood': {'pop': 0, 'tracts': 0},
 'Covington': {'pop': 0, 'tracts': 0},
 'Coweta': {'pop': 0, 'tracts': 0},
 'Cowley': {'pop': 0, 'tracts': 0},
 'Cowlitz': {'pop': 0, 'tracts': 0},
 'Craig': {'pop': 0, 'tracts': 0},
 'Craighead': {'pop': 0, 'tracts': 0},
 'Crane': {'pop': 0, 'tracts': 0},
 'Craven': {'pop': 0, 'tracts': 0},
 'Crawford': {'pop': 0, 'tracts': 0},
 'Creek': {'pop': 0, 'tracts': 0},
 'Crenshaw': {'pop': 0, 'tracts': 0},
 'Crisp': {'pop': 0, 'tracts': 0},
 'Crittenden': {'pop': 0, 'tracts': 0},
 'Crockett': {'pop': 0, 'tracts': 0},
 'Crook': {'pop': 0, 'tracts': 0},
 'Crosby': {'pop': 0, 'tracts': 0},
 'Cross': {'pop': 0, 'tracts': 0},
 'Crow Wing': {'pop': 0, 'tracts': 0},
 'Crowley': {'pop': 0, 'tracts': 0},
 'Culberson': {'pop': 0, 'tracts': 0},
 'Cullman': {'pop': 0, 'tracts': 0},
 'Culpeper': {'pop': 0, 'tracts': 0},
 'Cumberland': {'pop': 0, 'tracts': 0},
 'Cuming': {'pop': 0, 'tracts': 0},
 'Currituck': {'pop': 0, 'tracts': 0},
 'Curry': {'pop': 0, 'tracts': 0},
 'Custer': {'pop': 0, 'tracts': 0},
 'Cuyahoga': {'pop': 0, 'tracts': 0},
 'DC': {},
 'DE': {},
 'Dade': {'pop': 0, 'tracts': 0},
 'Daggett': {'pop': 0, 'tracts': 0},
 'Dakota': {'pop': 0, 'tracts': 0},
 'Dale': {'pop': 0, 'tracts': 0},
 'Dallam': {'pop': 0, 'tracts': 0},
 'Dallas': {'pop': 0, 'tracts': 0},
 'Dane': {'pop': 0, 'tracts': 0},
 'Daniels': {'pop': 0, 'tracts': 0},
 'Danville': {'pop': 0, 'tracts': 0},
 'Dare': {'pop': 0, 'tracts': 0},
 'Darke': {'pop': 0, 'tracts': 0},
 'Darlington': {'pop': 0, 'tracts': 0},
 'Dauphin': {'pop': 0, 'tracts': 0},
 'Davidson': {'pop': 0, 'tracts': 0},
 'Davie': {'pop': 0, 'tracts': 0},
 'Daviess': {'pop': 0, 'tracts': 0},
 'Davis': {'pop': 0, 'tracts': 0},
 'Davison': {'pop': 0, 'tracts': 0},
 'Dawes': {'pop': 0, 'tracts': 0},
 'Dawson': {'pop': 0, 'tracts': 0},
 'Day': {'pop': 0, 'tracts': 0},
 'De Baca': {'pop': 0, 'tracts': 0},
 'De Soto': {'pop': 0, 'tracts': 0},
 'De Witt': {'pop': 0, 'tracts': 0},
 'DeKalb': {'pop': 0, 'tracts': 0},
 'DeSoto': {'pop': 0, 'tracts': 0},
 'DeWitt': {'pop': 0, 'tracts': 0},
 'Deaf Smith': {'pop': 0, 'tracts': 0},
 'Dearborn': {'pop': 0, 'tracts': 0},
 'Decatur': {'pop': 0, 'tracts': 0},
 'Deer Lodge': {'pop': 0, 'tracts': 0},
 'Defiance': {'pop': 0, 'tracts': 0},
 'Del Norte': {'pop': 0, 'tracts': 0},
 'Delaware': {'pop': 0, 'tracts': 0},
 'Delta': {'pop': 0, 'tracts': 0},
 'Denali': {'pop': 0, 'tracts': 0},
 'Dent': {'pop': 0, 'tracts': 0},
 'Denton': {'pop': 0, 'tracts': 0},
 'Denver': {'pop': 0, 'tracts': 0},
 'Des Moines': {'pop': 0, 'tracts': 0},
 'Deschutes': {'pop': 0, 'tracts': 0},
 'Desha': {'pop': 0, 'tracts': 0},
 'Deuel': {'pop': 0, 'tracts': 0},
 'Dewey': {'pop': 0, 'tracts': 0},
 'Dickens': {'pop': 0, 'tracts': 0},
 'Dickenson': {'pop': 0, 'tracts': 0},
 'Dickey': {'pop': 0, 'tracts': 0},
 'Dickinson': {'pop': 0, 'tracts': 0},
 'Dickson': {'pop': 0, 'tracts': 0},
 'Dillingham': {'pop': 0, 'tracts': 0},
 'Dillon': {'pop': 0, 'tracts': 0},
 'Dimmit': {'pop': 0, 'tracts': 0},
 'Dinwiddie': {'pop': 0, 'tracts': 0},
 'District of Columbia': {'pop': 0, 'tracts': 0},
 'Divide': {'pop': 0, 'tracts': 0},
 'Dixie': {'pop': 0, 'tracts': 0},
 'Dixon': {'pop': 0, 'tracts': 0},
 'Doddridge': {'pop': 0, 'tracts': 0},
 'Dodge': {'pop': 0, 'tracts': 0},
 'Dolores': {'pop': 0, 'tracts': 0},
 'Dona Ana': {'pop': 0, 'tracts': 0},
 'Doniphan': {'pop': 0, 'tracts': 0},
 'Donley': {'pop': 0, 'tracts': 0},
 'Dooly': {'pop': 0, 'tracts': 0},
 'Door': {'pop': 0, 'tracts': 0},
 'Dorchester': {'pop': 0, 'tracts': 0},
 'Dougherty': {'pop': 0, 'tracts': 0},
 'Douglas': {'pop': 0, 'tracts': 0},
 'Drew': {'pop': 0, 'tracts': 0},
 'DuPage': {'pop': 0, 'tracts': 0},
 'Dubois': {'pop': 0, 'tracts': 0},
 'Dubuque': {'pop': 0, 'tracts': 0},
 'Duchesne': {'pop': 0, 'tracts': 0},
 'Dukes': {'pop': 0, 'tracts': 0},
 'Dundy': {'pop': 0, 'tracts': 0},
 'Dunklin': {'pop': 0, 'tracts': 0},
 'Dunn': {'pop': 0, 'tracts': 0},
 'Duplin': {'pop': 0, 'tracts': 0},
 'Durham': {'pop': 0, 'tracts': 0},
 'Dutchess': {'pop': 0, 'tracts': 0},
 'Duval': {'pop': 0, 'tracts': 0},
 'Dyer': {'pop': 0, 'tracts': 0},
 'Eagle': {'pop': 0, 'tracts': 0},
 'Early': {'pop': 0, 'tracts': 0},
 'East Baton Rouge': {'pop': 0, 'tracts': 0},
 'East Carroll': {'pop': 0, 'tracts': 0},
 'East Feliciana': {'pop': 0, 'tracts': 0},
 'Eastland': {'pop': 0, 'tracts': 0},
 'Eaton': {'pop': 0, 'tracts': 0},
 'Eau Claire': {'pop': 0, 'tracts': 0},
 'Echols': {'pop': 0, 'tracts': 0},
 'Ector': {'pop': 0, 'tracts': 0},
 'Eddy': {'pop': 0, 'tracts': 0},
 'Edgar': {'pop': 0, 'tracts': 0},
 'Edgecombe': {'pop': 0, 'tracts': 0},
 'Edgefield': {'pop': 0, 'tracts': 0},
 'Edmonson': {'pop': 0, 'tracts': 0},
 'Edmunds': {'pop': 0, 'tracts': 0},
 'Edwards': {'pop': 0, 'tracts': 0},
 'Effingham': {'pop': 0, 'tracts': 0},
 'El Dorado': {'pop': 0, 'tracts': 0},
 'El Paso': {'pop': 0, 'tracts': 0},
 'Elbert': {'pop': 0, 'tracts': 0},
 'Elk': {'pop': 0, 'tracts': 0},
 'Elkhart': {'pop': 0, 'tracts': 0},
 'Elko': {'pop': 0, 'tracts': 0},
 'Elliott': {'pop': 0, 'tracts': 0},
 'Ellis': {'pop': 0, 'tracts': 0},
 'Ellsworth': {'pop': 0, 'tracts': 0},
 'Elmore': {'pop': 0, 'tracts': 0},
 'Emanuel': {'pop': 0, 'tracts': 0},
 'Emery': {'pop': 0, 'tracts': 0},
 'Emmet': {'pop': 0, 'tracts': 0},
 'Emmons': {'pop': 0, 'tracts': 0},
 'Emporia': {'pop': 0, 'tracts': 0},
 'Erath': {'pop': 0, 'tracts': 0},
 'Erie': {'pop': 0, 'tracts': 0},
 'Escambia': {'pop': 0, 'tracts': 0},
 'Esmeralda': {'pop': 0, 'tracts': 0},
 'Essex': {'pop': 0, 'tracts': 0},
 'Estill': {'pop': 0, 'tracts': 0},
 'Etowah': {'pop': 0, 'tracts': 0},
 'Eureka': {'pop': 0, 'tracts': 0},
 'Evangeline': {'pop': 0, 'tracts': 0},
 'Evans': {'pop': 0, 'tracts': 0},
 'FL': {},
 'Fairbanks North Star': {'pop': 0, 'tracts': 0},
 'Fairfax': {'pop': 0, 'tracts': 0},
 'Fairfax City': {'pop': 0, 'tracts': 0},
 'Fairfield': {'pop': 0, 'tracts': 0},
 'Fall River': {'pop': 0, 'tracts': 0},
 'Fallon': {'pop': 0, 'tracts': 0},
 'Falls': {'pop': 0, 'tracts': 0},
 'Falls Church': {'pop': 0, 'tracts': 0},
 'Fannin': {'pop': 0, 'tracts': 0},
 'Faribault': {'pop': 0, 'tracts': 0},
 'Faulk': {'pop': 0, 'tracts': 0},
 'Faulkner': {'pop': 0, 'tracts': 0},
 'Fauquier': {'pop': 0, 'tracts': 0},
 'Fayette': {'pop': 0, 'tracts': 0},
 'Fentress': {'pop': 0, 'tracts': 0},
 'Fergus': {'pop': 0, 'tracts': 0},
 'Ferry': {'pop': 0, 'tracts': 0},
 'Fillmore': {'pop': 0, 'tracts': 0},
 'Finney': {'pop': 0, 'tracts': 0},
 'Fisher': {'pop': 0, 'tracts': 0},
 'Flagler': {'pop': 0, 'tracts': 0},
 'Flathead': {'pop': 0, 'tracts': 0},
 'Fleming': {'pop': 0, 'tracts': 0},
 'Florence': {'pop': 0, 'tracts': 0},
 'Floyd': {'pop': 0, 'tracts': 0},
 'Fluvanna': {'pop': 0, 'tracts': 0},
 'Foard': {'pop': 0, 'tracts': 0},
 'Fond du Lac': {'pop': 0, 'tracts': 0},
 'Ford': {'pop': 0, 'tracts': 0},
 'Forest': {'pop': 0, 'tracts': 0},
 'Forrest': {'pop': 0, 'tracts': 0},
 'Forsyth': {'pop': 0, 'tracts': 0},
 'Fort Bend': {'pop': 0, 'tracts': 0},
 'Foster': {'pop': 0, 'tracts': 0},
 'Fountain': {'pop': 0, 'tracts': 0},
 'Franklin': {'pop': 0, 'tracts': 0},
 'Franklin City': {'pop': 0, 'tracts': 0},
 'Frederick': {'pop': 0, 'tracts': 0},
 'Fredericksburg': {'pop': 0, 'tracts': 0},
 'Freeborn': {'pop': 0, 'tracts': 0},
 'Freestone': {'pop': 0, 'tracts': 0},
 'Fremont': {'pop': 0, 'tracts': 0},
 'Fresno': {'pop': 0, 'tracts': 0},
 'Frio': {'pop': 0, 'tracts': 0},
 'Frontier': {'pop': 0, 'tracts': 0},
 'Fulton': {'pop': 0, 'tracts': 0},
 'Furnas': {'pop': 0, 'tracts': 0},
 'GA': {},
 'Gadsden': {'pop': 0, 'tracts': 0},
 'Gage': {'pop': 0, 'tracts': 0},
 'Gaines': {'pop': 0, 'tracts': 0},
 'Galax': {'pop': 0, 'tracts': 0},
 'Gallatin': {'pop': 0, 'tracts': 0},
 'Gallia': {'pop': 0, 'tracts': 0},
 'Galveston': {'pop': 0, 'tracts': 0},
 'Garden': {'pop': 0, 'tracts': 0},
 'Garfield': {'pop': 0, 'tracts': 0},
 'Garland': {'pop': 0, 'tracts': 0},
 'Garrard': {'pop': 0, 'tracts': 0},
 'Garrett': {'pop': 0, 'tracts': 0},
 'Garvin': {'pop': 0, 'tracts': 0},
 'Garza': {'pop': 0, 'tracts': 0},
 'Gasconade': {'pop': 0, 'tracts': 0},
 'Gaston': {'pop': 0, 'tracts': 0},
 'Gates': {'pop': 0, 'tracts': 0},
 'Geary': {'pop': 0, 'tracts': 0},
 'Geauga': {'pop': 0, 'tracts': 0},
 'Gem': {'pop': 0, 'tracts': 0},
 'Genesee': {'pop': 0, 'tracts': 0},
 'Geneva': {'pop': 0, 'tracts': 0},
 'Gentry': {'pop': 0, 'tracts': 0},
 'George': {'pop': 0, 'tracts': 0},
 'Georgetown': {'pop': 0, 'tracts': 0},
 'Gibson': {'pop': 0, 'tracts': 0},
 'Gila': {'pop': 0, 'tracts': 0},
 'Gilchrist': {'pop': 0, 'tracts': 0},
 'Giles': {'pop': 0, 'tracts': 0},
 'Gillespie': {'pop': 0, 'tracts': 0},
 'Gilliam': {'pop': 0, 'tracts': 0},
 'Gilmer': {'pop': 0, 'tracts': 0},
 'Gilpin': {'pop': 0, 'tracts': 0},
 'Glacier': {'pop': 0, 'tracts': 0},
 'Glades': {'pop': 0, 'tracts': 0},
 'Gladwin': {'pop': 0, 'tracts': 0},
 'Glascock': {'pop': 0, 'tracts': 0},
 'Glasscock': {'pop': 0, 'tracts': 0},
 'Glenn': {'pop': 0, 'tracts': 0},
 'Gloucester': {'pop': 0, 'tracts': 0},
 'Glynn': {'pop': 0, 'tracts': 0},
 'Gogebic': {'pop': 0, 'tracts': 0},
 'Golden Valley': {'pop': 0, 'tracts': 0},
 'Goliad': {'pop': 0, 'tracts': 0},
 'Gonzales': {'pop': 0, 'tracts': 0},
 'Goochland': {'pop': 0, 'tracts': 0},
 'Goodhue': {'pop': 0, 'tracts': 0},
 'Gooding': {'pop': 0, 'tracts': 0},
 'Gordon': {'pop': 0, 'tracts': 0},
 'Goshen': {'pop': 0, 'tracts': 0},
 'Gosper': {'pop': 0, 'tracts': 0},
 'Gove': {'pop': 0, 'tracts': 0},
 'Grady': {'pop': 0, 'tracts': 0},
 'Grafton': {'pop': 0, 'tracts': 0},
 'Graham': {'pop': 0, 'tracts': 0},
 'Grainger': {'pop': 0, 'tracts': 0},
 'Grand': {'pop': 0, 'tracts': 0},
 'Grand Forks': {'pop': 0, 'tracts': 0},
 'Grand Isle': {'pop': 0, 'tracts': 0},
 'Grand Traverse': {'pop': 0, 'tracts': 0},
 'Granite': {'pop': 0, 'tracts': 0},
 'Grant': {'pop': 0, 'tracts': 0},
 'Granville': {'pop': 0, 'tracts': 0},
 'Gratiot': {'pop': 0, 'tracts': 0},
 'Graves': {'pop': 0, 'tracts': 0},
 'Gray': {'pop': 0, 'tracts': 0},
 'Grays Harbor': {'pop': 0, 'tracts': 0},
 'Grayson': {'pop': 0, 'tracts': 0},
 'Greeley': {'pop': 0, 'tracts': 0},
 'Green': {'pop': 0, 'tracts': 0},
 'Green Lake': {'pop': 0, 'tracts': 0},
 'Greenbrier': {'pop': 0, 'tracts': 0},
 'Greene': {'pop': 0, 'tracts': 0},
 'Greenlee': {'pop': 0, 'tracts': 0},
 'Greensville': {'pop': 0, 'tracts': 0},
 'Greenup': {'pop': 0, 'tracts': 0},
 'Greenville': {'pop': 0, 'tracts': 0},
 'Greenwood': {'pop': 0, 'tracts': 0},
 'Greer': {'pop': 0, 'tracts': 0},
 'Gregg': {'pop': 0, 'tracts': 0},
 'Gregory': {'pop': 0, 'tracts': 0},
 'Grenada': {'pop': 0, 'tracts': 0},
 'Griggs': {'pop': 0, 'tracts': 0},
 'Grimes': {'pop': 0, 'tracts': 0},
 'Grundy': {'pop': 0, 'tracts': 0},
 'Guadalupe': {'pop': 0, 'tracts': 0},
 'Guernsey': {'pop': 0, 'tracts': 0},
 'Guilford': {'pop': 0, 'tracts': 0},
 'Gulf': {'pop': 0, 'tracts': 0},
 'Gunnison': {'pop': 0, 'tracts': 0},
 'Guthrie': {'pop': 0, 'tracts': 0},
 'Gwinnett': {'pop': 0, 'tracts': 0},
 'HI': {},
 'Haakon': {'pop': 0, 'tracts': 0},
 'Habersham': {'pop': 0, 'tracts': 0},
 'Haines': {'pop': 0, 'tracts': 0},
 'Hale': {'pop': 0, 'tracts': 0},
 'Halifax': {'pop': 0, 'tracts': 0},
 'Hall': {'pop': 0, 'tracts': 0},
 'Hamblen': {'pop': 0, 'tracts': 0},
 'Hamilton': {'pop': 0, 'tracts': 0},
 'Hamlin': {'pop': 0, 'tracts': 0},
 'Hampden': {'pop': 0, 'tracts': 0},
 'Hampshire': {'pop': 0, 'tracts': 0},
 'Hampton': {'pop': 0, 'tracts': 0},
 'Hancock': {'pop': 0, 'tracts': 0},
 'Hand': {'pop': 0, 'tracts': 0},
 'Hanover': {'pop': 0, 'tracts': 0},
 'Hansford': {'pop': 0, 'tracts': 0},
 'Hanson': {'pop': 0, 'tracts': 0},
 'Haralson': {'pop': 0, 'tracts': 0},
 'Hardee': {'pop': 0, 'tracts': 0},
 'Hardeman': {'pop': 0, 'tracts': 0},
 'Hardin': {'pop': 0, 'tracts': 0},
 'Harding': {'pop': 0, 'tracts': 0},
 'Hardy': {'pop': 0, 'tracts': 0},
 'Harford': {'pop': 0, 'tracts': 0},
 'Harlan': {'pop': 0, 'tracts': 0},
 'Harmon': {'pop': 0, 'tracts': 0},
 'Harnett': {'pop': 0, 'tracts': 0},
 'Harney': {'pop': 0, 'tracts': 0},
 'Harper': {'pop': 0, 'tracts': 0},
 'Harris': {'pop': 0, 'tracts': 0},
 'Harrison': {'pop': 0, 'tracts': 0},
 'Harrisonburg': {'pop': 0, 'tracts': 0},
 'Hart': {'pop': 0, 'tracts': 0},
 'Hartford': {'pop': 0, 'tracts': 0},
 'Hartley': {'pop': 0, 'tracts': 0},
 'Harvey': {'pop': 0, 'tracts': 0},
 'Haskell': {'pop': 0, 'tracts': 0},
 'Hawaii': {'pop': 0, 'tracts': 0},
 'Hawkins': {'pop': 0, 'tracts': 0},
 'Hayes': {'pop': 0, 'tracts': 0},
 'Hays': {'pop': 0, 'tracts': 0},
 'Haywood': {'pop': 0, 'tracts': 0},
 'Heard': {'pop': 0, 'tracts': 0},
 'Hemphill': {'pop': 0, 'tracts': 0},
 'Hempstead': {'pop': 0, 'tracts': 0},
 'Henderson': {'pop': 0, 'tracts': 0},
 'Hendricks': {'pop': 0, 'tracts': 0},
 'Hendry': {'pop': 0, 'tracts': 0},
 'Hennepin': {'pop': 0, 'tracts': 0},
 'Henrico': {'pop': 0, 'tracts': 0},
 'Henry': {'pop': 0, 'tracts': 0},
 'Herkimer': {'pop': 0, 'tracts': 0},
 'Hernando': {'pop': 0, 'tracts': 0},
 'Hertford': {'pop': 0, 'tracts': 0},
 'Hettinger': {'pop': 0, 'tracts': 0},
 'Hickman': {'pop': 0, 'tracts': 0},
 'Hickory': {'pop': 0, 'tracts': 0},
 'Hidalgo': {'pop': 0, 'tracts': 0},
 'Highland': {'pop': 0, 'tracts': 0},
 'Highlands': {'pop': 0, 'tracts': 0},
 'Hill': {'pop': 0, 'tracts': 0},
 'Hillsborough': {'pop': 0, 'tracts': 0},
 'Hillsdale': {'pop': 0, 'tracts': 0},
 'Hinds': {'pop': 0, 'tracts': 0},
 'Hinsdale': {'pop': 0, 'tracts': 0},
 'Hitchcock': {'pop': 0, 'tracts': 0},
 'Hocking': {'pop': 0, 'tracts': 0},
 'Hockley': {'pop': 0, 'tracts': 0},
 'Hodgeman': {'pop': 0, 'tracts': 0},
 'Hoke': {'pop': 0, 'tracts': 0},
 'Holmes': {'pop': 0, 'tracts': 0},
 'Holt': {'pop': 0, 'tracts': 0},
 'Honolulu': {'pop': 0, 'tracts': 0},
 'Hood': {'pop': 0, 'tracts': 0},
 'Hood River': {'pop': 0, 'tracts': 0},
 'Hooker': {'pop': 0, 'tracts': 0},
 'Hoonah-Angoon': {'pop': 0, 'tracts': 0},
 'Hopewell': {'pop': 0, 'tracts': 0},
 'Hopkins': {'pop': 0, 'tracts': 0},
 'Horry': {'pop': 0, 'tracts': 0},
 'Hot Spring': {'pop': 0, 'tracts': 0},
 'Hot Springs': {'pop': 0, 'tracts': 0},
 'Houghton': {'pop': 0, 'tracts': 0},
 'Houston': {'pop': 0, 'tracts': 0},
 'Howard': {'pop': 0, 'tracts': 0},
 'Howell': {'pop': 0, 'tracts': 0},
 'Hubbard': {'pop': 0, 'tracts': 0},
 'Hudson': {'pop': 0, 'tracts': 0},
 'Hudspeth': {'pop': 0, 'tracts': 0},
 'Huerfano': {'pop': 0, 'tracts': 0},
 'Hughes': {'pop': 0, 'tracts': 0},
 'Humboldt': {'pop': 0, 'tracts': 0},
 'Humphreys': {'pop': 0, 'tracts': 0},
 'Hunt': {'pop': 0, 'tracts': 0},
 'Hunterdon': {'pop': 0, 'tracts': 0},
 'Huntingdon': {'pop': 0, 'tracts': 0},
 'Huntington': {'pop': 0, 'tracts': 0},
 'Huron': {'pop': 0, 'tracts': 0},
 'Hutchinson': {'pop': 0, 'tracts': 0},
 'Hyde': {'pop': 0, 'tracts': 0},
 'IA': {},
 'ID': {},
 'IL': {},
 'IN': {},
 'Iberia': {'pop': 0, 'tracts': 0},
 'Iberville': {'pop': 0, 'tracts': 0},
 'Ida': {'pop': 0, 'tracts': 0},
 'Idaho': {'pop': 0, 'tracts': 0},
 'Imperial': {'pop': 0, 'tracts': 0},
 'Independence': {'pop': 0, 'tracts': 0},
 'Indian River': {'pop': 0, 'tracts': 0},
 'Indiana': {'pop': 0, 'tracts': 0},
 'Ingham': {'pop': 0, 'tracts': 0},
 'Inyo': {'pop': 0, 'tracts': 0},
 'Ionia': {'pop': 0, 'tracts': 0},
 'Iosco': {'pop': 0, 'tracts': 0},
 'Iowa': {'pop': 0, 'tracts': 0},
 'Iredell': {'pop': 0, 'tracts': 0},
 'Irion': {'pop': 0, 'tracts': 0},
 'Iron': {'pop': 0, 'tracts': 0},
 'Iroquois': {'pop': 0, 'tracts': 0},
 'Irwin': {'pop': 0, 'tracts': 0},
 'Isabella': {'pop': 0, 'tracts': 0},
 'Isanti': {'pop': 0, 'tracts': 0},
 'Island': {'pop': 0, 'tracts': 0},
 'Isle of Wight': {'pop': 0, 'tracts': 0},
 'Issaquena': {'pop': 0, 'tracts': 0},
 'Itasca': {'pop': 0, 'tracts': 0},
 'Itawamba': {'pop': 0, 'tracts': 0},
 'Izard': {'pop': 0, 'tracts': 0},
 'Jack': {'pop': 0, 'tracts': 0},
 'Jackson': {'pop': 0, 'tracts': 0},
 'James City': {'pop': 0, 'tracts': 0},
 'Jasper': {'pop': 0, 'tracts': 0},
 'Jay': {'pop': 0, 'tracts': 0},
 'Jeff Davis': {'pop': 0, 'tracts': 0},
 'Jefferson': {'pop': 0, 'tracts': 0},
 'Jefferson Davis': {'pop': 0, 'tracts': 0},
 'Jenkins': {'pop': 0, 'tracts': 0},
 'Jennings': {'pop': 0, 'tracts': 0},
 'Jerauld': {'pop': 0, 'tracts': 0},
 'Jerome': {'pop': 0, 'tracts': 0},
 'Jersey': {'pop': 0, 'tracts': 0},
 'Jessamine': {'pop': 0, 'tracts': 0},
 'Jewell': {'pop': 0, 'tracts': 0},
 'Jim Hogg': {'pop': 0, 'tracts': 0},
 'Jim Wells': {'pop': 0, 'tracts': 0},
 'Jo Daviess': {'pop': 0, 'tracts': 0},
 'Johnson': {'pop': 0, 'tracts': 0},
 'Johnston': {'pop': 0, 'tracts': 0},
 'Jones': {'pop': 0, 'tracts': 0},
 'Josephine': {'pop': 0, 'tracts': 0},
 'Juab': {'pop': 0, 'tracts': 0},
 'Judith Basin': {'pop': 0, 'tracts': 0},
 'Juneau': {'pop': 0, 'tracts': 0},
 'Juniata': {'pop': 0, 'tracts': 0},
 'KS': {},
 'KY': {},
 'Kalamazoo': {'pop': 0, 'tracts': 0},
 'Kalawao': {'pop': 0, 'tracts': 0},
 'Kalkaska': {'pop': 0, 'tracts': 0},
 'Kanabec': {'pop': 0, 'tracts': 0},
 'Kanawha': {'pop': 0, 'tracts': 0},
 'Kandiyohi': {'pop': 0, 'tracts': 0},
 'Kane': {'pop': 0, 'tracts': 0},
 'Kankakee': {'pop': 0, 'tracts': 0},
 'Karnes': {'pop': 0, 'tracts': 0},
 'Kauai': {'pop': 0, 'tracts': 0},
 'Kaufman': {'pop': 0, 'tracts': 0},
 'Kay': {'pop': 0, 'tracts': 0},
 'Kearney': {'pop': 0, 'tracts': 0},
 'Kearny': {'pop': 0, 'tracts': 0},
 'Keith': {'pop': 0, 'tracts': 0},
 'Kemper': {'pop': 0, 'tracts': 0},
 'Kenai Peninsula': {'pop': 0, 'tracts': 0},
 'Kendall': {'pop': 0, 'tracts': 0},
 'Kenedy': {'pop': 0, 'tracts': 0},
 'Kennebec': {'pop': 0, 'tracts': 0},
 'Kenosha': {'pop': 0, 'tracts': 0},
 'Kent': {'pop': 0, 'tracts': 0},
 'Kenton': {'pop': 0, 'tracts': 0},
 'Keokuk': {'pop': 0, 'tracts': 0},
 'Kern': {'pop': 0, 'tracts': 0},
 'Kerr': {'pop': 0, 'tracts': 0},
 'Kershaw': {'pop': 0, 'tracts': 0},
 'Ketchikan Gateway': {'pop': 0, 'tracts': 0},
 'Kewaunee': {'pop': 0, 'tracts': 0},
 'Keweenaw': {'pop': 0, 'tracts': 0},
 'Keya Paha': {'pop': 0, 'tracts': 0},
 'Kidder': {'pop': 0, 'tracts': 0},
 'Kimball': {'pop': 0, 'tracts': 0},
 'Kimble': {'pop': 0, 'tracts': 0},
 'King': {'pop': 0, 'tracts': 0},
 'King George': {'pop': 0, 'tracts': 0},
 'King William': {'pop': 0, 'tracts': 0},
 'King and Queen': {'pop': 0, 'tracts': 0},
 'Kingfisher': {'pop': 0, 'tracts': 0},
 'Kingman': {'pop': 0, 'tracts': 0},
 'Kings': {'pop': 0, 'tracts': 0},
 'Kingsbury': {'pop': 0, 'tracts': 0},
 'Kinney': {'pop': 0, 'tracts': 0},
 'Kiowa': {'pop': 0, 'tracts': 0},
 'Kit Carson': {'pop': 0, 'tracts': 0},
 'Kitsap': {'pop': 0, 'tracts': 0},
 'Kittitas': {'pop': 0, 'tracts': 0},
 'Kittson': {'pop': 0, 'tracts': 0},
 'Klamath': {'pop': 0, 'tracts': 0},
 'Kleberg': {'pop': 0, 'tracts': 0},
 'Klickitat': {'pop': 0, 'tracts': 0},
 'Knott': {'pop': 0, 'tracts': 0},
 'Knox': {'pop': 0, 'tracts': 0},
 'Kodiak Island': {'pop': 0, 'tracts': 0},
 'Koochiching': {'pop': 0, 'tracts': 0},
 'Kootenai': {'pop': 0, 'tracts': 0},
 'Kosciusko': {'pop': 0, 'tracts': 0},
 'Kossuth': {'pop': 0, 'tracts': 0},
 'LA': {},
 'La Crosse': {'pop': 0, 'tracts': 0},
 'La Paz': {'pop': 0, 'tracts': 0},
 'La Plata': {'pop': 0, 'tracts': 0},
 'La Salle': {'pop': 0, 'tracts': 0},
 'LaGrange': {'pop': 0, 'tracts': 0},
 'LaMoure': {'pop': 0, 'tracts': 0},
 'LaPorte': {'pop': 0, 'tracts': 0},
 'Labette': {'pop': 0, 'tracts': 0},
 'Lac qui Parle': {'pop': 0, 'tracts': 0},
 'Lackawanna': {'pop': 0, 'tracts': 0},
 'Laclede': {'pop': 0, 'tracts': 0},
 'Lafayette': {'pop': 0, 'tracts': 0},
 'Lafourche': {'pop': 0, 'tracts': 0},
 'Lake': {'pop': 0, 'tracts': 0},
 'Lake and Peninsula': {'pop': 0, 'tracts': 0},
 'Lake of the Woods': {'pop': 0, 'tracts': 0},
 'Lamar': {'pop': 0, 'tracts': 0},
 'Lamb': {'pop': 0, 'tracts': 0},
 'Lamoille': {'pop': 0, 'tracts': 0},
 'Lampasas': {'pop': 0, 'tracts': 0},
 'Lancaster': {'pop': 0, 'tracts': 0},
 'Lander': {'pop': 0, 'tracts': 0},
 'Lane': {'pop': 0, 'tracts': 0},
 'Langlade': {'pop': 0, 'tracts': 0},
 'Lanier': {'pop': 0, 'tracts': 0},
 'Lapeer': {'pop': 0, 'tracts': 0},
 'Laramie': {'pop': 0, 'tracts': 0},
 'Larimer': {'pop': 0, 'tracts': 0},
 'Larue': {'pop': 0, 'tracts': 0},
 'Las Animas': {'pop': 0, 'tracts': 0},
 'Lassen': {'pop': 0, 'tracts': 0},
 'Latah': {'pop': 0, 'tracts': 0},
 'Latimer': {'pop': 0, 'tracts': 0},
 'Lauderdale': {'pop': 0, 'tracts': 0},
 'Laurel': {'pop': 0, 'tracts': 0},
 'Laurens': {'pop': 0, 'tracts': 0},
 'Lavaca': {'pop': 0, 'tracts': 0},
 'Lawrence': {'pop': 0, 'tracts': 0},
 'Le Flore': {'pop': 0, 'tracts': 0},
 'Le Sueur': {'pop': 0, 'tracts': 0},
 'Lea': {'pop': 0, 'tracts': 0},
 'Leake': {'pop': 0, 'tracts': 0},
 'Leavenworth': {'pop': 0, 'tracts': 0},
 'Lebanon': {'pop': 0, 'tracts': 0},
 'Lee': {'pop': 0, 'tracts': 0},
 'Leelanau': {'pop': 0, 'tracts': 0},
 'Leflore': {'pop': 0, 'tracts': 0},
 'Lehigh': {'pop': 0, 'tracts': 0},
 'Lemhi': {'pop': 0, 'tracts': 0},
 'Lenawee': {'pop': 0, 'tracts': 0},
 'Lenoir': {'pop': 0, 'tracts': 0},
 'Leon': {'pop': 0, 'tracts': 0},
 'Leslie': {'pop': 0, 'tracts': 0},
 'Letcher': {'pop': 0, 'tracts': 0},
 'Levy': {'pop': 0, 'tracts': 0},
 'Lewis': {'pop': 0, 'tracts': 0},
 'Lewis and Clark': {'pop': 0, 'tracts': 0},
 'Lexington': {'pop': 0, 'tracts': 0},
 'Liberty': {'pop': 0, 'tracts': 0},
 'Licking': {'pop': 0, 'tracts': 0},
 'Limestone': {'pop': 0, 'tracts': 0},
 'Lincoln': {'pop': 0, 'tracts': 0},
 'Linn': {'pop': 0, 'tracts': 0},
 'Lipscomb': {'pop': 0, 'tracts': 0},
 'Litchfield': {'pop': 0, 'tracts': 0},
 'Little River': {'pop': 0, 'tracts': 0},
 'Live Oak': {'pop': 0, 'tracts': 0},
 'Livingston': {'pop': 0, 'tracts': 0},
 'Llano': {'pop': 0, 'tracts': 0},
 'Logan': {'pop': 0, 'tracts': 0},
 'Long': {'pop': 0, 'tracts': 0},
 'Lonoke': {'pop': 0, 'tracts': 0},
 'Lorain': {'pop': 0, 'tracts': 0},
 'Los Alamos': {'pop': 0, 'tracts': 0},
 'Los Angeles': {'pop': 0, 'tracts': 0},
 'Loudon': {'pop': 0, 'tracts': 0},
 'Loudoun': {'pop': 0, 'tracts': 0},
 'Louisa': {'pop': 0, 'tracts': 0},
 'Loup': {'pop': 0, 'tracts': 0},
 'Love': {'pop': 0, 'tracts': 0},
 'Loving': {'pop': 0, 'tracts': 0},
 'Lowndes': {'pop': 0, 'tracts': 0},
 'Lubbock': {'pop': 0, 'tracts': 0},
 'Lucas': {'pop': 0, 'tracts': 0},
 'Luce': {'pop': 0, 'tracts': 0},
 'Lumpkin': {'pop': 0, 'tracts': 0},
 'Luna': {'pop': 0, 'tracts': 0},
 'Lunenburg': {'pop': 0, 'tracts': 0},
 'Luzerne': {'pop': 0, 'tracts': 0},
 'Lycoming': {'pop': 0, 'tracts': 0},
 'Lyman': {'pop': 0, 'tracts': 0},
 'Lynchburg': {'pop': 0, 'tracts': 0},
 'Lynn': {'pop': 0, 'tracts': 0},
 'Lyon': {'pop': 0, 'tracts': 0},
 'MA': {},
 'MD': {},
 'ME': {},
 'MI': {},
 'MN': {},
 'MO': {},
 'MS': {},
 'MT': {},
 'Mackinac': {'pop': 0, 'tracts': 0},
 'Macomb': {'pop': 0, 'tracts': 0},
 'Macon': {'pop': 0, 'tracts': 0},
 'Macoupin': {'pop': 0, 'tracts': 0},
 'Madera': {'pop': 0, 'tracts': 0},
 'Madison': {'pop': 0, 'tracts': 0},
 'Magoffin': {'pop': 0, 'tracts': 0},
 'Mahaska': {'pop': 0, 'tracts': 0},
 'Mahnomen': {'pop': 0, 'tracts': 0},
 'Mahoning': {'pop': 0, 'tracts': 0},
 'Major': {'pop': 0, 'tracts': 0},
 'Malheur': {'pop': 0, 'tracts': 0},
 'Manassas': {'pop': 0, 'tracts': 0},
 'Manassas Park': {'pop': 0, 'tracts': 0},
 'Manatee': {'pop': 0, 'tracts': 0},
 'Manistee': {'pop': 0, 'tracts': 0},
 'Manitowoc': {'pop': 0, 'tracts': 0},
 'Marathon': {'pop': 0, 'tracts': 0},
 'Marengo': {'pop': 0, 'tracts': 0},
 'Maricopa': {'pop': 0, 'tracts': 0},
 'Maries': {'pop': 0, 'tracts': 0},
 'Marin': {'pop': 0, 'tracts': 0},
 'Marinette': {'pop': 0, 'tracts': 0},
 'Marion': {'pop': 0, 'tracts': 0},
 'Mariposa': {'pop': 0, 'tracts': 0},
 'Marlboro': {'pop': 0, 'tracts': 0},
 'Marquette': {'pop': 0, 'tracts': 0},
 'Marshall': {'pop': 0, 'tracts': 0},
 'Martin': {'pop': 0, 'tracts': 0},
 'Martinsville': {'pop': 0, 'tracts': 0},
 'Mason': {'pop': 0, 'tracts': 0},
 'Massac': {'pop': 0, 'tracts': 0},
 'Matagorda': {'pop': 0, 'tracts': 0},
 'Matanuska-Susitna': {'pop': 0, 'tracts': 0},
 'Mathews': {'pop': 0, 'tracts': 0},
 'Maui': {'pop': 0, 'tracts': 0},
 'Maury': {'pop': 0, 'tracts': 0},
 'Maverick': {'pop': 0, 'tracts': 0},
 'Mayes': {'pop': 0, 'tracts': 0},
 'McClain': {'pop': 0, 'tracts': 0},
 'McCone': {'pop': 0, 'tracts': 0},
 'McCook': {'pop': 0, 'tracts': 0},
 'McCormick': {'pop': 0, 'tracts': 0},
 'McCracken': {'pop': 0, 'tracts': 0},
 'McCreary': {'pop': 0, 'tracts': 0},
 'McCulloch': {'pop': 0, 'tracts': 0},
 'McCurtain': {'pop': 0, 'tracts': 0},
 'McDonald': {'pop': 0, 'tracts': 0},
 'McDonough': {'pop': 0, 'tracts': 0},
 'McDowell': {'pop': 0, 'tracts': 0},
 'McDuffie': {'pop': 0, 'tracts': 0},
 'McHenry': {'pop': 0, 'tracts': 0},
 'McIntosh': {'pop': 0, 'tracts': 0},
 'McKean': {'pop': 0, 'tracts': 0},
 'McKenzie': {'pop': 0, 'tracts': 0},
 'McKinley': {'pop': 0, 'tracts': 0},
 'McLean': {'pop': 0, 'tracts': 0},
 'McLennan': {'pop': 0, 'tracts': 0},
 'McLeod': {'pop': 0, 'tracts': 0},
 'McMinn': {'pop': 0, 'tracts': 0},
 'McMullen': {'pop': 0, 'tracts': 0},
 'McNairy': {'pop': 0, 'tracts': 0},
 'McPherson': {'pop': 0, 'tracts': 0},
 'Meade': {'pop': 0, 'tracts': 0},
 'Meagher': {'pop': 0, 'tracts': 0},
 'Mecklenburg': {'pop': 0, 'tracts': 0},
 'Mecosta': {'pop': 0, 'tracts': 0},
 'Medina': {'pop': 0, 'tracts': 0},
 'Meeker': {'pop': 0, 'tracts': 0},
 'Meigs': {'pop': 0, 'tracts': 0},
 'Mellette': {'pop': 0, 'tracts': 0},
 'Menard': {'pop': 0, 'tracts': 0},
 'Mendocino': {'pop': 0, 'tracts': 0},
 'Menifee': {'pop': 0, 'tracts': 0},
 'Menominee': {'pop': 0, 'tracts': 0},
 'Merced': {'pop': 0, 'tracts': 0},
 'Mercer': {'pop': 0, 'tracts': 0},
 'Meriwether': {'pop': 0, 'tracts': 0},
 'Merrick': {'pop': 0, 'tracts': 0},
 'Merrimack': {'pop': 0, 'tracts': 0},
 'Mesa': {'pop': 0, 'tracts': 0},
 'Metcalfe': {'pop': 0, 'tracts': 0},
 'Miami': {'pop': 0, 'tracts': 0},
 'Miami-Dade': {'pop': 0, 'tracts': 0},
 'Middlesex': {'pop': 0, 'tracts': 0},
 'Midland': {'pop': 0, 'tracts': 0},
 'Mifflin': {'pop': 0, 'tracts': 0},
 'Milam': {'pop': 0, 'tracts': 0},
 'Millard': {'pop': 0, 'tracts': 0},
 'Mille Lacs': {'pop': 0, 'tracts': 0},
 'Miller': {'pop': 0, 'tracts': 0},
 'Mills': {'pop': 0, 'tracts': 0},
 'Milwaukee': {'pop': 0, 'tracts': 0},
 'Miner': {'pop': 0, 'tracts': 0},
 'Mineral': {'pop': 0, 'tracts': 0},
 'Mingo': {'pop': 0, 'tracts': 0},
 'Minidoka': {'pop': 0, 'tracts': 0},
 'Minnehaha': {'pop': 0, 'tracts': 0},
 'Missaukee': {'pop': 0, 'tracts': 0},
 'Mississippi': {'pop': 0, 'tracts': 0},
 'Missoula': {'pop': 0, 'tracts': 0},
 'Mitchell': {'pop': 0, 'tracts': 0},
 'Mobile': {'pop': 0, 'tracts': 0},
 'Modoc': {'pop': 0, 'tracts': 0},
 'Moffat': {'pop': 0, 'tracts': 0},
 'Mohave': {'pop': 0, 'tracts': 0},
 'Moniteau': {'pop': 0, 'tracts': 0},
 'Monmouth': {'pop': 0, 'tracts': 0},
 'Mono': {'pop': 0, 'tracts': 0},
 'Monona': {'pop': 0, 'tracts': 0},
 'Monongalia': {'pop': 0, 'tracts': 0},
 'Monroe': {'pop': 0, 'tracts': 0},
 'Montague': {'pop': 0, 'tracts': 0},
 'Montcalm': {'pop': 0, 'tracts': 0},
 'Monterey': {'pop': 0, 'tracts': 0},
 'Montezuma': {'pop': 0, 'tracts': 0},
 'Montgomery': {'pop': 0, 'tracts': 0},
 'Montmorency': {'pop': 0, 'tracts': 0},
 'Montour': {'pop': 0, 'tracts': 0},
 'Montrose': {'pop': 0, 'tracts': 0},
 'Moody': {'pop': 0, 'tracts': 0},
 'Moore': {'pop': 0, 'tracts': 0},
 'Mora': {'pop': 0, 'tracts': 0},
 'Morehouse': {'pop': 0, 'tracts': 0},
 'Morgan': {'pop': 0, 'tracts': 0},
 'Morrill': {'pop': 0, 'tracts': 0},
 'Morris': {'pop': 0, 'tracts': 0},
 'Morrison': {'pop': 0, 'tracts': 0},
 'Morrow': {'pop': 0, 'tracts': 0},
 'Morton': {'pop': 0, 'tracts': 0},
 'Motley': {'pop': 0, 'tracts': 0},
 'Moultrie': {'pop': 0, 'tracts': 0},
 'Mountrail': {'pop': 0, 'tracts': 0},
 'Mower': {'pop': 0, 'tracts': 0},
 'Muhlenberg': {'pop': 0, 'tracts': 0},
 'Multnomah': {'pop': 0, 'tracts': 0},
 'Murray': {'pop': 0, 'tracts': 0},
 'Muscatine': {'pop': 0, 'tracts': 0},
 'Muscogee': {'pop': 0, 'tracts': 0},
 'Muskegon': {'pop': 0, 'tracts': 0},
 'Muskingum': {'pop': 0, 'tracts': 0},
 'Muskogee': {'pop': 0, 'tracts': 0},
 'Musselshell': {'pop': 0, 'tracts': 0},
 'NC': {},
 'ND': {},
 'NE': {},
 'NH': {},
 'NJ': {},
 'NM': {},
 'NV': {},
 'NY': {},
 'Nacogdoches': {'pop': 0, 'tracts': 0},
 'Nance': {'pop': 0, 'tracts': 0},
 'Nantucket': {'pop': 0, 'tracts': 0},
 'Napa': {'pop': 0, 'tracts': 0},
 'Nash': {'pop': 0, 'tracts': 0},
 'Nassau': {'pop': 0, 'tracts': 0},
 'Natchitoches': {'pop': 0, 'tracts': 0},
 'Natrona': {'pop': 0, 'tracts': 0},
 'Navajo': {'pop': 0, 'tracts': 0},
 'Navarro': {'pop': 0, 'tracts': 0},
 'Nelson': {'pop': 0, 'tracts': 0},
 'Nemaha': {'pop': 0, 'tracts': 0},
 'Neosho': {'pop': 0, 'tracts': 0},
 'Neshoba': {'pop': 0, 'tracts': 0},
 'Ness': {'pop': 0, 'tracts': 0},
 'Nevada': {'pop': 0, 'tracts': 0},
 'New Castle': {'pop': 0, 'tracts': 0},
 'New Hanover': {'pop': 0, 'tracts': 0},
 'New Haven': {'pop': 0, 'tracts': 0},
 'New Kent': {'pop': 0, 'tracts': 0},
 'New London': {'pop': 0, 'tracts': 0},
 'New Madrid': {'pop': 0, 'tracts': 0},
 'New York': {'pop': 0, 'tracts': 0},
 'Newaygo': {'pop': 0, 'tracts': 0},
 'Newberry': {'pop': 0, 'tracts': 0},
 'Newport': {'pop': 0, 'tracts': 0},
 'Newport News': {'pop': 0, 'tracts': 0},
 'Newton': {'pop': 0, 'tracts': 0},
 'Nez Perce': {'pop': 0, 'tracts': 0},
 'Niagara': {'pop': 0, 'tracts': 0},
 'Nicholas': {'pop': 0, 'tracts': 0},
 'Nicollet': {'pop': 0, 'tracts': 0},
 'Niobrara': {'pop': 0, 'tracts': 0},
 'Noble': {'pop': 0, 'tracts': 0},
 'Nobles': {'pop': 0, 'tracts': 0},
 'Nodaway': {'pop': 0, 'tracts': 0},
 'Nolan': {'pop': 0, 'tracts': 0},
 'Nome': {'pop': 0, 'tracts': 0},
 'Norfolk': {'pop': 0, 'tracts': 0},
 'Norman': {'pop': 0, 'tracts': 0},
 'North Slope': {'pop': 0, 'tracts': 0},
 'Northampton': {'pop': 0, 'tracts': 0},
 'Northumberland': {'pop': 0, 'tracts': 0},
 'Northwest Arctic': {'pop': 0, 'tracts': 0},
 'Norton': {'pop': 0, 'tracts': 0},
 'Nottoway': {'pop': 0, 'tracts': 0},
 'Nowata': {'pop': 0, 'tracts': 0},
 'Noxubee': {'pop': 0, 'tracts': 0},
 'Nuckolls': {'pop': 0, 'tracts': 0},
 'Nueces': {'pop': 0, 'tracts': 0},
 'Nye': {'pop': 0, 'tracts': 0},
 "O'Brien": {'pop': 0, 'tracts': 0},
 'OH': {},
 'OK': {},
 'OR': {},
 'Oakland': {'pop': 0, 'tracts': 0},
 'Obion': {'pop': 0, 'tracts': 0},
 'Ocean': {'pop': 0, 'tracts': 0},
 'Oceana': {'pop': 0, 'tracts': 0},
 'Ochiltree': {'pop': 0, 'tracts': 0},
 'Oconee': {'pop': 0, 'tracts': 0},
 'Oconto': {'pop': 0, 'tracts': 0},
 'Ogemaw': {'pop': 0, 'tracts': 0},
 'Ogle': {'pop': 0, 'tracts': 0},
 'Oglethorpe': {'pop': 0, 'tracts': 0},
 'Ohio': {'pop': 0, 'tracts': 0},
 'Okaloosa': {'pop': 0, 'tracts': 0},
 'Okanogan': {'pop': 0, 'tracts': 0},
 'Okeechobee': {'pop': 0, 'tracts': 0},
 'Okfuskee': {'pop': 0, 'tracts': 0},
 'Oklahoma': {'pop': 0, 'tracts': 0},
 'Okmulgee': {'pop': 0, 'tracts': 0},
 'Oktibbeha': {'pop': 0, 'tracts': 0},
 'Oldham': {'pop': 0, 'tracts': 0},
 'Oliver': {'pop': 0, 'tracts': 0},
 'Olmsted': {'pop': 0, 'tracts': 0},
 'Oneida': {'pop': 0, 'tracts': 0},
 'Onondaga': {'pop': 0, 'tracts': 0},
 'Onslow': {'pop': 0, 'tracts': 0},
 'Ontario': {'pop': 0, 'tracts': 0},
 'Ontonagon': {'pop': 0, 'tracts': 0},
 'Orange': {'pop': 0, 'tracts': 0},
 'Orangeburg': {'pop': 0, 'tracts': 0},
 'Oregon': {'pop': 0, 'tracts': 0},
 'Orleans': {'pop': 0, 'tracts': 0},
 'Osage': {'pop': 0, 'tracts': 0},
 'Osborne': {'pop': 0, 'tracts': 0},
 'Osceola': {'pop': 0, 'tracts': 0},
 'Oscoda': {'pop': 0, 'tracts': 0},
 'Oswego': {'pop': 0, 'tracts': 0},
 'Otero': {'pop': 0, 'tracts': 0},
 'Otoe': {'pop': 0, 'tracts': 0},
 'Otsego': {'pop': 0, 'tracts': 0},
 'Ottawa': {'pop': 0, 'tracts': 0},
 'Otter Tail': {'pop': 0, 'tracts': 0},
 'Ouachita': {'pop': 0, 'tracts': 0},
 'Ouray': {'pop': 0, 'tracts': 0},
 'Outagamie': {'pop': 0, 'tracts': 0},
 'Overton': {'pop': 0, 'tracts': 0},
 'Owen': {'pop': 0, 'tracts': 0},
 'Owsley': {'pop': 0, 'tracts': 0},
 'Owyhee': {'pop': 0, 'tracts': 0},
 'Oxford': {'pop': 0, 'tracts': 0},
 'Ozark': {'pop': 0, 'tracts': 0},
 'Ozaukee': {'pop': 0, 'tracts': 0},
 'PA': {},
 'Pacific': {'pop': 0, 'tracts': 0},
 'Page': {'pop': 0, 'tracts': 0},
 'Palm Beach': {'pop': 0, 'tracts': 0},
 'Palo Alto': {'pop': 0, 'tracts': 0},
 'Palo Pinto': {'pop': 0, 'tracts': 0},
 'Pamlico': {'pop': 0, 'tracts': 0},
 'Panola': {'pop': 0, 'tracts': 0},
 'Park': {'pop': 0, 'tracts': 0},
 'Parke': {'pop': 0, 'tracts': 0},
 'Parker': {'pop': 0, 'tracts': 0},
 'Parmer': {'pop': 0, 'tracts': 0},
 'Pasco': {'pop': 0, 'tracts': 0},
 'Pasquotank': {'pop': 0, 'tracts': 0},
 'Passaic': {'pop': 0, 'tracts': 0},
 'Patrick': {'pop': 0, 'tracts': 0},
 'Paulding': {'pop': 0, 'tracts': 0},
 'Pawnee': {'pop': 0, 'tracts': 0},
 'Payette': {'pop': 0, 'tracts': 0},
 'Payne': {'pop': 0, 'tracts': 0},
 'Peach': {'pop': 0, 'tracts': 0},
 'Pearl River': {'pop': 0, 'tracts': 0},
 'Pecos': {'pop': 0, 'tracts': 0},
 'Pembina': {'pop': 0, 'tracts': 0},
 'Pemiscot': {'pop': 0, 'tracts': 0},
 'Pend Oreille': {'pop': 0, 'tracts': 0},
 'Pender': {'pop': 0, 'tracts': 0},
 'Pendleton': {'pop': 0, 'tracts': 0},
 'Pennington': {'pop': 0, 'tracts': 0},
 'Penobscot': {'pop': 0, 'tracts': 0},
 'Peoria': {'pop': 0, 'tracts': 0},
 'Pepin': {'pop': 0, 'tracts': 0},
 'Perkins': {'pop': 0, 'tracts': 0},
 'Perquimans': {'pop': 0, 'tracts': 0},
 'Perry': {'pop': 0, 'tracts': 0},
 'Pershing': {'pop': 0, 'tracts': 0},
 'Person': {'pop': 0, 'tracts': 0},
 'Petersburg': {'pop': 0, 'tracts': 0},
 'Petroleum': {'pop': 0, 'tracts': 0},
 'Pettis': {'pop': 0, 'tracts': 0},
 'Phelps': {'pop': 0, 'tracts': 0},
 'Philadelphia': {'pop': 0, 'tracts': 0},
 'Phillips': {'pop': 0, 'tracts': 0},
 'Piatt': {'pop': 0, 'tracts': 0},
 'Pickaway': {'pop': 0, 'tracts': 0},
 'Pickens': {'pop': 0, 'tracts': 0},
 'Pickett': {'pop': 0, 'tracts': 0},
 'Pierce': {'pop': 0, 'tracts': 0},
 'Pike': {'pop': 0, 'tracts': 0},
 'Pima': {'pop': 0, 'tracts': 0},
 'Pinal': {'pop': 0, 'tracts': 0},
 'Pine': {'pop': 0, 'tracts': 0},
 'Pinellas': {'pop': 0, 'tracts': 0},
 'Pipestone': {'pop': 0, 'tracts': 0},
 'Piscataquis': {'pop': 0, 'tracts': 0},
 'Pitkin': {'pop': 0, 'tracts': 0},
 'Pitt': {'pop': 0, 'tracts': 0},
 'Pittsburg': {'pop': 0, 'tracts': 0},
 'Pittsylvania': {'pop': 0, 'tracts': 0},
 'Piute': {'pop': 0, 'tracts': 0},
 'Placer': {'pop': 0, 'tracts': 0},
 'Plaquemines': {'pop': 0, 'tracts': 0},
 'Platte': {'pop': 0, 'tracts': 0},
 'Pleasants': {'pop': 0, 'tracts': 0},
 'Plumas': {'pop': 0, 'tracts': 0},
 'Plymouth': {'pop': 0, 'tracts': 0},
 'Pocahontas': {'pop': 0, 'tracts': 0},
 'Poinsett': {'pop': 0, 'tracts': 0},
 'Pointe Coupee': {'pop': 0, 'tracts': 0},
 'Polk': {'pop': 0, 'tracts': 0},
 'Pondera': {'pop': 0, 'tracts': 0},
 'Pontotoc': {'pop': 0, 'tracts': 0},
 'Pope': {'pop': 0, 'tracts': 0},
 'Poquoson': {'pop': 0, 'tracts': 0},
 'Portage': {'pop': 0, 'tracts': 0},
 'Porter': {'pop': 0, 'tracts': 0},
 'Portsmouth': {'pop': 0, 'tracts': 0},
 'Posey': {'pop': 0, 'tracts': 0},
 'Pottawatomie': {'pop': 0, 'tracts': 0},
 'Pottawattamie': {'pop': 0, 'tracts': 0},
 'Potter': {'pop': 0, 'tracts': 0},
 'Powder River': {'pop': 0, 'tracts': 0},
 'Powell': {'pop': 0, 'tracts': 0},
 'Power': {'pop': 0, 'tracts': 0},
 'Poweshiek': {'pop': 0, 'tracts': 0},
 'Powhatan': {'pop': 0, 'tracts': 0},
 'Prairie': {'pop': 0, 'tracts': 0},
 'Pratt': {'pop': 0, 'tracts': 0},
 'Preble': {'pop': 0, 'tracts': 0},
 'Prentiss': {'pop': 0, 'tracts': 0},
 'Presidio': {'pop': 0, 'tracts': 0},
 'Presque Isle': {'pop': 0, 'tracts': 0},
 'Preston': {'pop': 0, 'tracts': 0},
 'Price': {'pop': 0, 'tracts': 0},
 'Prince Edward': {'pop': 0, 'tracts': 0},
 'Prince George': {'pop': 0, 'tracts': 0},
 "Prince George's": {'pop': 0, 'tracts': 0},
 'Prince William': {'pop': 0, 'tracts': 0},
 'Prince of Wales-Hyder': {'pop': 0, 'tracts': 0},
 'Providence': {'pop': 0, 'tracts': 0},
 'Prowers': {'pop': 0, 'tracts': 0},
 'Pueblo': {'pop': 0, 'tracts': 0},
 'Pulaski': {'pop': 0, 'tracts': 0},
 'Pushmataha': {'pop': 0, 'tracts': 0},
 'Putnam': {'pop': 0, 'tracts': 0},
 'Quay': {'pop': 0, 'tracts': 0},
 "Queen Anne's": {'pop': 0, 'tracts': 0},
 'Queens': {'pop': 0, 'tracts': 0},
 'Quitman': {'pop': 0, 'tracts': 0},
 'RI': {},
 'Rabun': {'pop': 0, 'tracts': 0},
 'Racine': {'pop': 0, 'tracts': 0},
 'Radford': {'pop': 0, 'tracts': 0},
 'Rains': {'pop': 0, 'tracts': 0},
 'Raleigh': {'pop': 0, 'tracts': 0},
 'Ralls': {'pop': 0, 'tracts': 0},
 'Ramsey': {'pop': 0, 'tracts': 0},
 'Randall': {'pop': 0, 'tracts': 0},
 'Randolph': {'pop': 0, 'tracts': 0},
 'Rankin': {'pop': 0, 'tracts': 0},
 'Ransom': {'pop': 0, 'tracts': 0},
 'Rapides': {'pop': 0, 'tracts': 0},
 'Rappahannock': {'pop': 0, 'tracts': 0},
 'Ravalli': {'pop': 0, 'tracts': 0},
 'Rawlins': {'pop': 0, 'tracts': 0},
 'Ray': {'pop': 0, 'tracts': 0},
 'Reagan': {'pop': 0, 'tracts': 0},
 'Real': {'pop': 0, 'tracts': 0},
 'Red Lake': {'pop': 0, 'tracts': 0},
 'Red River': {'pop': 0, 'tracts': 0},
 'Red Willow': {'pop': 0, 'tracts': 0},
 'Redwood': {'pop': 0, 'tracts': 0},
 'Reeves': {'pop': 0, 'tracts': 0},
 'Refugio': {'pop': 0, 'tracts': 0},
 'Reno': {'pop': 0, 'tracts': 0},
 'Rensselaer': {'pop': 0, 'tracts': 0},
 'Renville': {'pop': 0, 'tracts': 0},
 'Republic': {'pop': 0, 'tracts': 0},
 'Reynolds': {'pop': 0, 'tracts': 0},
 'Rhea': {'pop': 0, 'tracts': 0},
 'Rice': {'pop': 0, 'tracts': 0},
 'Rich': {'pop': 0, 'tracts': 0},
 'Richardson': {'pop': 0, 'tracts': 0},
 'Richland': {'pop': 0, 'tracts': 0},
 'Richmond': {'pop': 0, 'tracts': 0},
 'Richmond City': {'pop': 0, 'tracts': 0},
 'Riley': {'pop': 0, 'tracts': 0},
 'Ringgold': {'pop': 0, 'tracts': 0},
 'Rio Arriba': {'pop': 0, 'tracts': 0},
 'Rio Blanco': {'pop': 0, 'tracts': 0},
 'Rio Grande': {'pop': 0, 'tracts': 0},
 'Ripley': {'pop': 0, 'tracts': 0},
 'Ritchie': {'pop': 0, 'tracts': 0},
 'Riverside': {'pop': 0, 'tracts': 0},
 'Roane': {'pop': 0, 'tracts': 0},
 'Roanoke': {'pop': 0, 'tracts': 0},
 'Roanoke City': {'pop': 0, 'tracts': 0},
 'Roberts': {'pop': 0, 'tracts': 0},
 'Robertson': {'pop': 0, 'tracts': 0},
 'Robeson': {'pop': 0, 'tracts': 0},
 'Rock': {'pop': 0, 'tracts': 0},
 'Rock Island': {'pop': 0, 'tracts': 0},
 'Rockbridge': {'pop': 0, 'tracts': 0},
 'Rockcastle': {'pop': 0, 'tracts': 0},
 'Rockdale': {'pop': 0, 'tracts': 0},
 'Rockingham': {'pop': 0, 'tracts': 0},
 'Rockland': {'pop': 0, 'tracts': 0},
 'Rockwall': {'pop': 0, 'tracts': 0},
 'Roger Mills': {'pop': 0, 'tracts': 0},
 'Rogers': {'pop': 0, 'tracts': 0},
 'Rolette': {'pop': 0, 'tracts': 0},
 'Rooks': {'pop': 0, 'tracts': 0},
 'Roosevelt': {'pop': 0, 'tracts': 0},
 'Roscommon': {'pop': 0, 'tracts': 0},
 'Roseau': {'pop': 0, 'tracts': 0},
 'Rosebud': {'pop': 0, 'tracts': 0},
 'Ross': {'pop': 0, 'tracts': 0},
 'Routt': {'pop': 0, 'tracts': 0},
 'Rowan': {'pop': 0, 'tracts': 0},
 'Runnels': {'pop': 0, 'tracts': 0},
 'Rush': {'pop': 0, 'tracts': 0},
 'Rusk': {'pop': 0, 'tracts': 0},
 'Russell': {'pop': 0, 'tracts': 0},
 'Rutherford': {'pop': 0, 'tracts': 0},
 'Rutland': {'pop': 0, 'tracts': 0},
 'SC': {},
 'SD': {},
 'Sabine': {'pop': 0, 'tracts': 0},
 'Sac': {'pop': 0, 'tracts': 0},
 'Sacramento': {'pop': 0, 'tracts': 0},
 'Sagadahoc': {'pop': 0, 'tracts': 0},
 'Saginaw': {'pop': 0, 'tracts': 0},
 'Saguache': {'pop': 0, 'tracts': 0},
 'Salem': {'pop': 0, 'tracts': 0},
 'Saline': {'pop': 0, 'tracts': 0},
 'Salt Lake': {'pop': 0, 'tracts': 0},
 'Saluda': {'pop': 0, 'tracts': 0},
 'Sampson': {'pop': 0, 'tracts': 0},
 'San Augustine': {'pop': 0, 'tracts': 0},
 'San Benito': {'pop': 0, 'tracts': 0},
 'San Bernardino': {'pop': 0, 'tracts': 0},
 'San Diego': {'pop': 0, 'tracts': 0},
 'San Francisco': {'pop': 0, 'tracts': 0},
 'San Jacinto': {'pop': 0, 'tracts': 0},
 'San Joaquin': {'pop': 0, 'tracts': 0},
 'San Juan': {'pop': 0, 'tracts': 0},
 'San Luis Obispo': {'pop': 0, 'tracts': 0},
 'San Mateo': {'pop': 0, 'tracts': 0},
 'San Miguel': {'pop': 0, 'tracts': 0},
 'San Patricio': {'pop': 0, 'tracts': 0},
 'San Saba': {'pop': 0, 'tracts': 0},
 'Sanborn': {'pop': 0, 'tracts': 0},
 'Sanders': {'pop': 0, 'tracts': 0},
 'Sandoval': {'pop': 0, 'tracts': 0},
 'Sandusky': {'pop': 0, 'tracts': 0},
 'Sangamon': {'pop': 0, 'tracts': 0},
 'Sanilac': {'pop': 0, 'tracts': 0},
 'Sanpete': {'pop': 0, 'tracts': 0},
 'Santa Barbara': {'pop': 0, 'tracts': 0},
 'Santa Clara': {'pop': 0, 'tracts': 0},
 'Santa Cruz': {'pop': 0, 'tracts': 0},
 'Santa Fe': {'pop': 0, 'tracts': 0},
 'Santa Rosa': {'pop': 0, 'tracts': 0},
 'Sarasota': {'pop': 0, 'tracts': 0},
 'Saratoga': {'pop': 0, 'tracts': 0},
 'Sargent': {'pop': 0, 'tracts': 0},
 'Sarpy': {'pop': 0, 'tracts': 0},
 'Sauk': {'pop': 0, 'tracts': 0},
 'Saunders': {'pop': 0, 'tracts': 0},
 'Sawyer': {'pop': 0, 'tracts': 0},
 'Schenectady': {'pop': 0, 'tracts': 0},
 'Schleicher': {'pop': 0, 'tracts': 0},
 'Schley': {'pop': 0, 'tracts': 0},
 'Schoharie': {'pop': 0, 'tracts': 0},
 'Schoolcraft': {'pop': 0, 'tracts': 0},
 'Schuyler': {'pop': 0, 'tracts': 0},
 'Schuylkill': {'pop': 0, 'tracts': 0},
 'Scioto': {'pop': 0, 'tracts': 0},
 'Scotland': {'pop': 0, 'tracts': 0},
 'Scott': {'pop': 0, 'tracts': 0},
 'Scotts Bluff': {'pop': 0, 'tracts': 0},
 'Screven': {'pop': 0, 'tracts': 0},
 'Scurry': {'pop': 0, 'tracts': 0},
 'Searcy': {'pop': 0, 'tracts': 0},
 'Sebastian': {'pop': 0, 'tracts': 0},
 'Sedgwick': {'pop': 0, 'tracts': 0},
 'Seminole': {'pop': 0, 'tracts': 0},
 'Seneca': {'pop': 0, 'tracts': 0},
 'Sequatchie': {'pop': 0, 'tracts': 0},
 'Sequoyah': {'pop': 0, 'tracts': 0},
 'Sevier': {'pop': 0, 'tracts': 0},
 'Seward': {'pop': 0, 'tracts': 0},
 'Shackelford': {'pop': 0, 'tracts': 0},
 'Shannon': {'pop': 0, 'tracts': 0},
 'Sharkey': {'pop': 0, 'tracts': 0},
 'Sharp': {'pop': 0, 'tracts': 0},
 'Shasta': {'pop': 0, 'tracts': 0},
 'Shawano': {'pop': 0, 'tracts': 0},
 'Shawnee': {'pop': 0, 'tracts': 0},
 'Sheboygan': {'pop': 0, 'tracts': 0},
 'Shelby': {'pop': 0, 'tracts': 0},
 'Shenandoah': {'pop': 0, 'tracts': 0},
 'Sherburne': {'pop': 0, 'tracts': 0},
 'Sheridan': {'pop': 0, 'tracts': 0},
 'Sherman': {'pop': 0, 'tracts': 0},
 'Shiawassee': {'pop': 0, 'tracts': 0},
 'Shoshone': {'pop': 0, 'tracts': 0},
 'Sibley': {'pop': 0, 'tracts': 0},
 'Sierra': {'pop': 0, 'tracts': 0},
 'Silver Bow': {'pop': 0, 'tracts': 0},
 'Simpson': {'pop': 0, 'tracts': 0},
 'Sioux': {'pop': 0, 'tracts': 0},
 'Siskiyou': {'pop': 0, 'tracts': 0},
 'Sitka': {'pop': 0, 'tracts': 0},
 'Skagit': {'pop': 0, 'tracts': 0},
 'Skagway': {'pop': 0, 'tracts': 0},
 'Skamania': {'pop': 0, 'tracts': 0},
 'Slope': {'pop': 0, 'tracts': 0},
 'Smith': {'pop': 0, 'tracts': 0},
 'Smyth': {'pop': 0, 'tracts': 0},
 'Snohomish': {'pop': 0, 'tracts': 0},
 'Snyder': {'pop': 0, 'tracts': 0},
 'Socorro': {'pop': 0, 'tracts': 0},
 'Solano': {'pop': 0, 'tracts': 0},
 'Somerset': {'pop': 0, 'tracts': 0},
 'Somervell': {'pop': 0, 'tracts': 0},
 'Sonoma': {'pop': 0, 'tracts': 0},
 'Southampton': {'pop': 0, 'tracts': 0},
 'Southeast Fairbanks': {'pop': 0, 'tracts': 0},
 'Spalding': {'pop': 0, 'tracts': 0},
 'Spartanburg': {'pop': 0, 'tracts': 0},
 'Spencer': {'pop': 0, 'tracts': 0},
 'Spink': {'pop': 0, 'tracts': 0},
 'Spokane': {'pop': 0, 'tracts': 0},
 'Spotsylvania': {'pop': 0, 'tracts': 0},
 'St. Bernard': {'pop': 0, 'tracts': 0},
 'St. Charles': {'pop': 0, 'tracts': 0},
 'St. Clair': {'pop': 0, 'tracts': 0},
 'St. Croix': {'pop': 0, 'tracts': 0},
 'St. Francis': {'pop': 0, 'tracts': 0},
 'St. Francois': {'pop': 0, 'tracts': 0},
 'St. Helena': {'pop': 0, 'tracts': 0},
 'St. James': {'pop': 0, 'tracts': 0},
 'St. John the Baptist': {'pop': 0, 'tracts': 0},
 'St. Johns': {'pop': 0, 'tracts': 0},
 'St. Joseph': {'pop': 0, 'tracts': 0},
 'St. Landry': {'pop': 0, 'tracts': 0},
 'St. Lawrence': {'pop': 0, 'tracts': 0},
 'St. Louis': {'pop': 0, 'tracts': 0},
 'St. Louis City': {'pop': 0, 'tracts': 0},
 'St. Lucie': {'pop': 0, 'tracts': 0},
 'St. Martin': {'pop': 0, 'tracts': 0},
 'St. Mary': {'pop': 0, 'tracts': 0},
 "St. Mary's": {'pop': 0, 'tracts': 0},
 'St. Tammany': {'pop': 0, 'tracts': 0},
 'Stafford': {'pop': 0, 'tracts': 0},
 'Stanislaus': {'pop': 0, 'tracts': 0},
 'Stanley': {'pop': 0, 'tracts': 0},
 'Stanly': {'pop': 0, 'tracts': 0},
 'Stanton': {'pop': 0, 'tracts': 0},
 'Stark': {'pop': 0, 'tracts': 0},
 'Starke': {'pop': 0, 'tracts': 0},
 'Starr': {'pop': 0, 'tracts': 0},
 'Staunton': {'pop': 0, 'tracts': 0},
 'Ste. Genevieve': {'pop': 0, 'tracts': 0},
 'Stearns': {'pop': 0, 'tracts': 0},
 'Steele': {'pop': 0, 'tracts': 0},
 'Stephens': {'pop': 0, 'tracts': 0},
 'Stephenson': {'pop': 0, 'tracts': 0},
 'Sterling': {'pop': 0, 'tracts': 0},
 'Steuben': {'pop': 0, 'tracts': 0},
 'Stevens': {'pop': 0, 'tracts': 0},
 'Stewart': {'pop': 0, 'tracts': 0},
 'Stillwater': {'pop': 0, 'tracts': 0},
 'Stoddard': {'pop': 0, 'tracts': 0},
 'Stokes': {'pop': 0, 'tracts': 0},
 'Stone': {'pop': 0, 'tracts': 0},
 'Stonewall': {'pop': 0, 'tracts': 0},
 'Storey': {'pop': 0, 'tracts': 0},
 'Story': {'pop': 0, 'tracts': 0},
 'Strafford': {'pop': 0, 'tracts': 0},
 'Stutsman': {'pop': 0, 'tracts': 0},
 'Sublette': {'pop': 0, 'tracts': 0},
 'Suffolk': {'pop': 0, 'tracts': 0},
 'Sullivan': {'pop': 0, 'tracts': 0},
 'Sully': {'pop': 0, 'tracts': 0},
 'Summers': {'pop': 0, 'tracts': 0},
 'Summit': {'pop': 0, 'tracts': 0},
 'Sumner': {'pop': 0, 'tracts': 0},
 'Sumter': {'pop': 0, 'tracts': 0},
 'Sunflower': {'pop': 0, 'tracts': 0},
 'Surry': {'pop': 0, 'tracts': 0},
 'Susquehanna': {'pop': 0, 'tracts': 0},
 'Sussex': {'pop': 0, 'tracts': 0},
 'Sutter': {'pop': 0, 'tracts': 0},
 'Sutton': {'pop': 0, 'tracts': 0},
 'Suwannee': {'pop': 0, 'tracts': 0},
 'Swain': {'pop': 0, 'tracts': 0},
 'Sweet Grass': {'pop': 0, 'tracts': 0},
 'Sweetwater': {'pop': 0, 'tracts': 0},
 'Swift': {'pop': 0, 'tracts': 0},
 'Swisher': {'pop': 0, 'tracts': 0},
 'Switzerland': {'pop': 0, 'tracts': 0},
 'TN': {},
 'TX': {},
 'Talbot': {'pop': 0, 'tracts': 0},
 'Taliaferro': {'pop': 0, 'tracts': 0},
 'Talladega': {'pop': 0, 'tracts': 0},
 'Tallahatchie': {'pop': 0, 'tracts': 0},
 'Tallapoosa': {'pop': 0, 'tracts': 0},
 'Tama': {'pop': 0, 'tracts': 0},
 'Taney': {'pop': 0, 'tracts': 0},
 'Tangipahoa': {'pop': 0, 'tracts': 0},
 'Taos': {'pop': 0, 'tracts': 0},
 'Tarrant': {'pop': 0, 'tracts': 0},
 'Tate': {'pop': 0, 'tracts': 0},
 'Tattnall': {'pop': 0, 'tracts': 0},
 'Taylor': {'pop': 0, 'tracts': 0},
 'Tazewell': {'pop': 0, 'tracts': 0},
 'Tehama': {'pop': 0, 'tracts': 0},
 'Telfair': {'pop': 0, 'tracts': 0},
 'Teller': {'pop': 0, 'tracts': 0},
 'Tensas': {'pop': 0, 'tracts': 0},
 'Terrebonne': {'pop': 0, 'tracts': 0},
 'Terrell': {'pop': 0, 'tracts': 0},
 'Terry': {'pop': 0, 'tracts': 0},
 'Teton': {'pop': 0, 'tracts': 0},
 'Texas': {'pop': 0, 'tracts': 0},
 'Thayer': {'pop': 0, 'tracts': 0},
 'Thomas': {'pop': 0, 'tracts': 0},
 'Throckmorton': {'pop': 0, 'tracts': 0},
 'Thurston': {'pop': 0, 'tracts': 0},
 'Tift': {'pop': 0, 'tracts': 0},
 'Tillamook': {'pop': 0, 'tracts': 0},
 'Tillman': {'pop': 0, 'tracts': 0},
 'Tioga': {'pop': 0, 'tracts': 0},
 'Tippah': {'pop': 0, 'tracts': 0},
 'Tippecanoe': {'pop': 0, 'tracts': 0},
 'Tipton': {'pop': 0, 'tracts': 0},
 'Tishomingo': {'pop': 0, 'tracts': 0},
 'Titus': {'pop': 0, 'tracts': 0},
 'Todd': {'pop': 0, 'tracts': 0},
 'Tolland': {'pop': 0, 'tracts': 0},
 'Tom Green': {'pop': 0, 'tracts': 0},
 'Tompkins': {'pop': 0, 'tracts': 0},
 'Tooele': {'pop': 0, 'tracts': 0},
 'Toole': {'pop': 0, 'tracts': 0},
 'Toombs': {'pop': 0, 'tracts': 0},
 'Torrance': {'pop': 0, 'tracts': 0},
 'Towner': {'pop': 0, 'tracts': 0},
 'Towns': {'pop': 0, 'tracts': 0},
 'Traill': {'pop': 0, 'tracts': 0},
 'Transylvania': {'pop': 0, 'tracts': 0},
 'Traverse': {'pop': 0, 'tracts': 0},
 'Travis': {'pop': 0, 'tracts': 0},
 'Treasure': {'pop': 0, 'tracts': 0},
 'Trego': {'pop': 0, 'tracts': 0},
 'Trempealeau': {'pop': 0, 'tracts': 0},
 'Treutlen': {'pop': 0, 'tracts': 0},
 'Trigg': {'pop': 0, 'tracts': 0},
 'Trimble': {'pop': 0, 'tracts': 0},
 'Trinity': {'pop': 0, 'tracts': 0},
 'Tripp': {'pop': 0, 'tracts': 0},
 'Troup': {'pop': 0, 'tracts': 0},
 'Trousdale': {'pop': 0, 'tracts': 0},
 'Trumbull': {'pop': 0, 'tracts': 0},
 'Tucker': {'pop': 0, 'tracts': 0},
 'Tulare': {'pop': 0, 'tracts': 0},
 'Tulsa': {'pop': 0, 'tracts': 0},
 'Tunica': {'pop': 0, 'tracts': 0},
 'Tuolumne': {'pop': 0, 'tracts': 0},
 'Turner': {'pop': 0, 'tracts': 0},
 'Tuscaloosa': {'pop': 0, 'tracts': 0},
 'Tuscarawas': {'pop': 0, 'tracts': 0},
 'Tuscola': {'pop': 0, 'tracts': 0},
 'Twiggs': {'pop': 0, 'tracts': 0},
 'Twin Falls': {'pop': 0, 'tracts': 0},
 'Tyler': {'pop': 0, 'tracts': 0},
 'Tyrrell': {'pop': 0, 'tracts': 0},
 'UT': {},
 'Uinta': {'pop': 0, 'tracts': 0},
 'Uintah': {'pop': 0, 'tracts': 0},
 'Ulster': {'pop': 0, 'tracts': 0},
 'Umatilla': {'pop': 0, 'tracts': 0},
 'Unicoi': {'pop': 0, 'tracts': 0},
 'Union': {'pop': 0, 'tracts': 0},
 'Upshur': {'pop': 0, 'tracts': 0},
 'Upson': {'pop': 0, 'tracts': 0},
 'Upton': {'pop': 0, 'tracts': 0},
 'Utah': {'pop': 0, 'tracts': 0},
 'Uvalde': {'pop': 0, 'tracts': 0},
 'VA': {},
 'VT': {},
 'Val Verde': {'pop': 0, 'tracts': 0},
 'Valdez-Cordova': {'pop': 0, 'tracts': 0},
 'Valencia': {'pop': 0, 'tracts': 0},
 'Valley': {'pop': 0, 'tracts': 0},
 'Van Buren': {'pop': 0, 'tracts': 0},
 'Van Wert': {'pop': 0, 'tracts': 0},
 'Van Zandt': {'pop': 0, 'tracts': 0},
 'Vance': {'pop': 0, 'tracts': 0},
 'Vanderburgh': {'pop': 0, 'tracts': 0},
 'Venango': {'pop': 0, 'tracts': 0},
 'Ventura': {'pop': 0, 'tracts': 0},
 'Vermilion': {'pop': 0, 'tracts': 0},
 'Vermillion': {'pop': 0, 'tracts': 0},
 'Vernon': {'pop': 0, 'tracts': 0},
 'Victoria': {'pop': 0, 'tracts': 0},
 'Vigo': {'pop': 0, 'tracts': 0},
 'Vilas': {'pop': 0, 'tracts': 0},
 'Vinton': {'pop': 0, 'tracts': 0},
 'Virginia Beach': {'pop': 0, 'tracts': 0},
 'Volusia': {'pop': 0, 'tracts': 0},
 'WA': {},
 'WI': {},
 'WV': {},
 'WY': {},
 'Wabash': {'pop': 0, 'tracts': 0},
 'Wabasha': {'pop': 0, 'tracts': 0},
 'Wabaunsee': {'pop': 0, 'tracts': 0},
 'Wade Hampton': {'pop': 0, 'tracts': 0},
 'Wadena': {'pop': 0, 'tracts': 0},
 'Wagoner': {'pop': 0, 'tracts': 0},
 'Wahkiakum': {'pop': 0, 'tracts': 0},
 'Wake': {'pop': 0, 'tracts': 0},
 'Wakulla': {'pop': 0, 'tracts': 0},
 'Waldo': {'pop': 0, 'tracts': 0},
 'Walker': {'pop': 0, 'tracts': 0},
 'Walla Walla': {'pop': 0, 'tracts': 0},
 'Wallace': {'pop': 0, 'tracts': 0},
 'Waller': {'pop': 0, 'tracts': 0},
 'Wallowa': {'pop': 0, 'tracts': 0},
 'Walsh': {'pop': 0, 'tracts': 0},
 'Walthall': {'pop': 0, 'tracts': 0},
 'Walton': {'pop': 0, 'tracts': 0},
 'Walworth': {'pop': 0, 'tracts': 0},
 'Wapello': {'pop': 0, 'tracts': 0},
 'Ward': {'pop': 0, 'tracts': 0},
 'Ware': {'pop': 0, 'tracts': 0},
 'Warren': {'pop': 0, 'tracts': 0},
 'Warrick': {'pop': 0, 'tracts': 0},
 'Wasatch': {'pop': 0, 'tracts': 0},
 'Wasco': {'pop': 0, 'tracts': 0},
 'Waseca': {'pop': 0, 'tracts': 0},
 'Washakie': {'pop': 0, 'tracts': 0},
 'Washburn': {'pop': 0, 'tracts': 0},
 'Washington': {'pop': 0, 'tracts': 0},
 'Washita': {'pop': 0, 'tracts': 0},
 'Washoe': {'pop': 0, 'tracts': 0},
 'Washtenaw': {'pop': 0, 'tracts': 0},
 'Watauga': {'pop': 0, 'tracts': 0},
 'Watonwan': {'pop': 0, 'tracts': 0},
 'Waukesha': {'pop': 0, 'tracts': 0},
 'Waupaca': {'pop': 0, 'tracts': 0},
 'Waushara': {'pop': 0, 'tracts': 0},
 'Wayne': {'pop': 0, 'tracts': 0},
 'Waynesboro': {'pop': 0, 'tracts': 0},
 'Weakley': {'pop': 0, 'tracts': 0},
 'Webb': {'pop': 0, 'tracts': 0},
 'Weber': {'pop': 0, 'tracts': 0},
 'Webster': {'pop': 0, 'tracts': 0},
 'Weld': {'pop': 0, 'tracts': 0},
 'Wells': {'pop': 0, 'tracts': 0},
 'West Baton Rouge': {'pop': 0, 'tracts': 0},
 'West Carroll': {'pop': 0, 'tracts': 0},
 'West Feliciana': {'pop': 0, 'tracts': 0},
 'Westchester': {'pop': 0, 'tracts': 0},
 'Westmoreland': {'pop': 0, 'tracts': 0},
 'Weston': {'pop': 0, 'tracts': 0},
 'Wetzel': {'pop': 0, 'tracts': 0},
 'Wexford': {'pop': 0, 'tracts': 0},
 'Wharton': {'pop': 0, 'tracts': 0},
 'Whatcom': {'pop': 0, 'tracts': 0},
 'Wheatland': {'pop': 0, 'tracts': 0},
 'Wheeler': {'pop': 0, 'tracts': 0},
 'White': {'pop': 0, 'tracts': 0},
 'White Pine': {'pop': 0, 'tracts': 0},
 'Whiteside': {'pop': 0, 'tracts': 0},
 'Whitfield': {'pop': 0, 'tracts': 0},
 'Whitley': {'pop': 0, 'tracts': 0},
 'Whitman': {'pop': 0, 'tracts': 0},
 'Wibaux': {'pop': 0, 'tracts': 0},
 'Wichita': {'pop': 0, 'tracts': 0},
 'Wicomico': {'pop': 0, 'tracts': 0},
 'Wilbarger': {'pop': 0, 'tracts': 0},
 'Wilcox': {'pop': 0, 'tracts': 0},
 'Wilkes': {'pop': 0, 'tracts': 0},
 'Wilkin': {'pop': 0, 'tracts': 0},
 'Wilkinson': {'pop': 0, 'tracts': 0},
 'Will': {'pop': 0, 'tracts': 0},
 'Willacy': {'pop': 0, 'tracts': 0},
 'Williams': {'pop': 0, 'tracts': 0},
 'Williamsburg': {'pop': 0, 'tracts': 0},
 'Williamson': {'pop': 0, 'tracts': 0},
 'Wilson': {'pop': 0, 'tracts': 0},
 'Winchester': {'pop': 0, 'tracts': 0},
 'Windham': {'pop': 0, 'tracts': 0},
 'Windsor': {'pop': 0, 'tracts': 0},
 'Winkler': {'pop': 0, 'tracts': 0},
 'Winn': {'pop': 0, 'tracts': 0},
 'Winnebago': {'pop': 0, 'tracts': 0},
 'Winneshiek': {'pop': 0, 'tracts': 0},
 'Winona': {'pop': 0, 'tracts': 0},
 'Winston': {'pop': 0, 'tracts': 0},
 'Wirt': {'pop': 0, 'tracts': 0},
 'Wise': {'pop': 0, 'tracts': 0},
 'Wolfe': {'pop': 0, 'tracts': 0},
 'Wood': {'pop': 0, 'tracts': 0},
 'Woodbury': {'pop': 0, 'tracts': 0},
 'Woodford': {'pop': 0, 'tracts': 0},
 'Woodruff': {'pop': 0, 'tracts': 0},
 'Woods': {'pop': 0, 'tracts': 0},
 'Woodson': {'pop': 0, 'tracts': 0},
 'Woodward': {'pop': 0, 'tracts': 0},
 'Worcester': {'pop': 0, 'tracts': 0},
 'Worth': {'pop': 0, 'tracts': 0},
 'Wrangell': {'pop': 0, 'tracts': 0},
 'Wright': {'pop': 0, 'tracts': 0},
 'Wyandot': {'pop': 0, 'tracts': 0},
 'Wyandotte': {'pop': 0, 'tracts': 0},
 'Wyoming': {'pop': 0, 'tracts': 0},
 'Wythe': {'pop': 0, 'tracts': 0},
 'Yadkin': {'pop': 0, 'tracts': 0},
 'Yakima': {'pop': 0, 'tracts': 0},
 'Yakutat': {'pop': 0, 'tracts': 0},
 'Yalobusha': {'pop': 0, 'tracts': 0},
 'Yamhill': {'pop': 0, 'tracts': 0},
 'Yancey': {'pop': 0, 'tracts': 0},
 'Yankton': {'pop': 0, 'tracts': 0},
 'Yates': {'pop': 0, 'tracts': 0},
 'Yavapai': {'pop': 0, 'tracts': 0},
 'Yazoo': {'pop': 0, 'tracts': 0},
 'Yell': {'pop': 0, 'tracts': 0},
 'Yellow Medicine': {'pop': 0, 'tracts': 0},
 'Yellowstone': {'pop': 0, 'tracts': 0},
 'Yoakum': {'pop': 0, 'tracts': 0},
 'Yolo': {'pop': 0, 'tracts': 0},
 'York': {'pop': 0, 'tracts': 0},
 'Young': {'pop': 0, 'tracts': 0},
 'Yuba': {'pop': 0, 'tracts': 0},
 'Yukon-Koyukuk': {'pop': 0, 'tracts': 0},
 'Yuma': {'pop': 0, 'tracts': 0},
 'Zapata': {'pop': 0, 'tracts': 0},
 'Zavala': {'pop': 0, 'tracts': 0},
 'Ziebach': {'pop': 0, 'tracts': 0}}